import { SongsSearchResponse } from "@templates/search";

export const chartUpdated = "1688630567";

export const faq = {
  category: [
    { type: "qna", category: "전체" },
    { type: "qna", category: "기타" },
    { type: "qna", category: "리스트" },
    { type: "qna", category: "회원" },
    { type: "qna", category: "플레이어" },
  ],
  article: [
    {
      question: "왁뮤에서 노래를 들어도 유튜브 조회수에 반영이 되나요?",
      description:
        "반영됩니다. \n왁타버스 뮤직은 유튜브 기반 플레이어를 사용하여 재생되는 모든 음악이 조회수로 집계됩니다.",
      createAt: 1687696656,
      category: { type: "qna", category: "기타" },
    },
    {
      question: "나만의 플레이리스트 만들 수 있나요?",
      description:
        "만들 수 있습니다.\n로그인 후 보관함에서 '리스트 만들기'를 선택하면 생성이 가능합니다. 생성된 리스트는 앱과 연동이 됩니다.",
      createAt: 1687697114,
      category: { type: "qna", category: "리스트" },
    },
    {
      question: "회원탈퇴는 어떻게 할 수 있나요?",
      description:
        "'보관함' > 오른쪽 상단 '건의사항' > 오른쪽 상단 '회원탈퇴' 버튼을 통해 탈퇴할 수 있습니다.",
      createAt: 1687697156,
      category: { type: "qna", category: "회원" },
    },
    {
      question: "프로필을 편집할 수 있나요?",
      description:
        "‘보관함’ > 왼쪽 상단 ‘프로필’을 선택하면 프로필 사진과 닉네임 모두 편집 가능합니다.",
      createAt: 1687697201,
      category: { type: "qna", category: "회원" },
    },
    {
      question: "데이터 소모량이 어떻게 되나요?",
      description: "유튜브 영상과 비슷합니다.",
      createAt: 1687697242,
      category: { type: "qna", category: "기타" },
    },
    {
      question: "왁뮤목록에 없는 노래를 추가하려고 하는데 어떻게 해야 하나요?",
      description: "‘보관함’ > ‘건의사항’ > ‘문의하기’를 이용해주세요.",
      createAt: 1687697306,
      category: { type: "qna", category: "기타" },
    },
    {
      question: "썸네일 말고 영상이 나오게는 할 수 없나요?",
      description:
        "영상이 플레이되면 기능에 제약이 생기는 문제가 많아서 썸네일만 표시되도록 조정했습니다.",
      createAt: 1687697382,
      category: { type: "qna", category: "플레이어" },
    },
    {
      question: "특정 노래들이 다른 노래에 비해서 소리가 너무 작아요.",
      description:
        "유튜브에서 그대로 가져오기 때문에 원본이 소리가 작으면 작게 들립니다.",
      createAt: 1687697451,
      category: { type: "qna", category: "플레이어" },
    },
    {
      question: "가사가 아직 안나오는 곡들이 있어요.",
      description:
        "작업 중입니다. 가내수공업으로 직접 제작 중이니 이해 부탁드립니다.",
      createAt: 1687697499,
      category: { type: "qna", category: "기타" },
    },
    {
      question: "PC와 모바일이 연동이 되나요?",
      description:
        "계정이 연동되어 있어 내 리스트, 좋아요 등의 기능을 두 플랫폼 모두 사용하실 수 있습니다.",
      createAt: 1687697585,
      category: { type: "qna", category: "기타" },
    },
    {
      question: "iOS 백그라운드 재생 진입 시 잠시 끊겨요",
      description: "개발자 : “어쩔 수 없음”",
      createAt: 1687697669,
      category: { type: "qna", category: "플레이어" },
    },
    {
      question:
        "블루투스 연결이 끊기면 노래가 일시정지되지 않아서 노래가 나와요. 암살 방지 기능 안되나요?",
      description: "개발자 : “힘든 상황…”",
      createAt: 1687697703,
      category: { type: "qna", category: "기타" },
    },
    {
      question: "버그제보는 아무나 이용 가능한가요?",
      description:
        "네 가능합니다. \n다만 정말 필요할 경우에만 이용 바랍니다. 많은 데이터 이동으로 인한 서버 부담이 이어질 수 있습니다.",
      createAt: 1687697741,
      category: { type: "qna", category: "기타" },
    },
    {
      question: "안드로이드 백그라운드 재생 중 다음 곡으로 넘어가질 않아요",
      description:
        "배터리 절약 옵션과 충돌이 날 수 있습니다.\n'설정 > 애플리케이션 > 왁타버스 뮤직 > 배터리 > 제한 없음' 순서대로 설정 부탁드립니다.",
      createAt: 1689083213,
      category: { type: "qna", category: "플레이어" },
    },
  ],
};

export const userInfo = {
  username: "왁타버스 뮤직",
  via: "카카오톡",
};

export const hourlyChart = [
  {
    songId: "QgMFpuos4Rg",
    title: "LOCKDOWN",
    artist: "이세계아이돌",
    remix: "",
    reaction: "",
    date: 230622,
    start: 0,
    end: 0,
    like: 1,
    hourly: { views: 3004739, increase: 2894, last: 1 },
  },
  {
    songId: "SXE-gIU3yJs",
    title: "고멤가요제 MASHUP",
    artist: "아이네",
    remix: "",
    reaction: "",
    date: 221201,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 5105546, increase: 740, last: 3 },
  },
  {
    songId: "iLXmqg_HHRA",
    title: "스물셋",
    artist: "비챤",
    remix: "",
    reaction: "5pIR8SGmgkg",
    date: 230617,
    start: 0,
    end: 192,
    like: 0,
    hourly: { views: 883975, increase: 710, last: 2 },
  },
  {
    songId: "fgSXAKsq-Vo",
    title: "리와인드 (RE:WIND)",
    artist: "이세계아이돌",
    remix: "",
    reaction: "",
    date: 211222,
    start: 0,
    end: 270,
    like: 0,
    hourly: { views: 15676550, increase: 654, last: 4 },
  },
  {
    songId: "aK76gQHIm04",
    title: "징버거 궁시렁 Remix",
    artist: "징버거",
    remix: "레이지스피크",
    reaction: "zxVzfCawDyE",
    date: 221220,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 3028840, increase: 578, last: 5 },
  },
  {
    songId: "IK-z7xhiKB0",
    title: "PINK VENOM",
    artist: "저세계아이돌",
    remix: "",
    reaction: "",
    date: 230702,
    start: 0,
    end: 186,
    like: 0,
    hourly: { views: 283411, increase: 558, last: 6 },
  },
  {
    songId: "EA_gei4Fcxk",
    title: "Hot Summer",
    artist: "러브 미쓰 피쓰",
    remix: "",
    reaction: "",
    date: 230612,
    start: 0,
    end: 229,
    like: 0,
    hourly: { views: 1300552, increase: 479, last: 14 },
  },
  {
    songId: "DPEtmqvaKqY",
    title: "팬서비스",
    artist: "고세구",
    remix: "",
    reaction: "",
    date: 220111,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 9540461, increase: 462, last: 8 },
  },
  {
    songId: "qunpFTI90sU",
    title: "강풍 올백머리",
    artist: "징버거",
    remix: "",
    reaction: "JOWZiZWNjHg",
    date: 230426,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 2321698, increase: 462, last: 16 },
  },
  {
    songId: "gEKKOrvh92Y",
    title: "아이돌 #Shorts",
    artist: "징버거",
    remix: "",
    reaction: "",
    date: 230612,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 2545825, increase: 449, last: 13 },
  },
  {
    songId: "l8e1Byk1Dx0",
    title: "TRUE LOVER (ft. 행주)",
    artist: "이세계오빠들",
    remix: "",
    reaction: "",
    date: 220918,
    start: 0,
    end: 200,
    like: 0,
    hourly: { views: 8805280, increase: 446, last: 7 },
  },
  {
    songId: "_lwD3ILdKi0",
    title: "무희",
    artist: "뢴트게늄",
    remix: "",
    reaction: "",
    date: 230225,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 2979593, increase: 444, last: 9 },
  },
  {
    songId: "6hEvgKL0ClA",
    title: "Promise",
    artist: "릴파",
    remix: "",
    reaction: "",
    date: 211229,
    start: 0,
    end: 243,
    like: 0,
    hourly: { views: 7047127, increase: 440, last: 10 },
  },
  {
    songId: "mqcGI5QGmzk",
    title: "계절범죄",
    artist: "이노리(지하돌), 흰젓가락(주폭), 우앵두(지하돌)",
    remix: "",
    reaction: "CN8cZabPVgM",
    date: 230630,
    start: 0,
    end: 229,
    like: 0,
    hourly: { views: 118503, increase: 430, last: 15 },
  },
  {
    songId: "S2I6tRQtR58",
    title: "Grrr",
    artist: "왁컬로이두",
    remix: "큐컴버",
    reaction: "beBJf_eifnY",
    date: 230702,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 132930, increase: 422, last: 27 },
  },
  {
    songId: "p9TFQ9ySJLs",
    title: "봄도둑",
    artist: "징버거",
    remix: "",
    reaction: "",
    date: 230430,
    start: 0,
    end: 288,
    like: 0,
    hourly: { views: 1084810, increase: 402, last: 18 },
  },
  {
    songId: "lLIpFxWtqCQ",
    title:
      "사랑하긴 했었나요 스쳐가는 인연이었나요 짧지않은 우리 함께했던 시간들이 자꾸 내 마음을 가둬두네 (Baby I need you)",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 221216,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 3307240, increase: 371, last: 12 },
  },
  {
    songId: "KjySNSxgg3U",
    title: "저곳으로",
    artist: "징버거",
    remix: "",
    reaction: "GZDoPjRpAoQ",
    date: 230531,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 1632994, increase: 335, last: 11 },
  },
  {
    songId: "eWaBljLkd08",
    title: "Ballin'",
    artist: "징버거",
    remix: "",
    reaction: "",
    date: 230525,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 580998, increase: 333, last: 21 },
  },
  {
    songId: "K8WC6uWyC9I",
    title: "그냥 살아! (ft. 비챤)",
    artist: "김피탕앤짬뽕",
    remix: "",
    reaction: "",
    date: 220918,
    start: 16,
    end: 0,
    like: 0,
    hourly: { views: 7952476, increase: 319, last: 23 },
  },
  {
    songId: "63zca7DAoFA",
    title: "이쪼기야 도와줘 #Shorts",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 230701,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 153038, increase: 310, last: 36 },
  },
  {
    songId: "dZc2K3lLcz4",
    title: "U R Man (암욜맨)",
    artist: "아닌말곰",
    remix: "",
    reaction: "dgqT4ORWMEo",
    date: 230612,
    start: 0,
    end: 201,
    like: 0,
    hourly: { views: 921127, increase: 305, last: 29 },
  },
  {
    songId: "z6RSOiYOVuQ",
    title: "아이돌 (ft. 비챤)",
    artist: "주르르",
    remix: "",
    reaction: "",
    date: 230517,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 1362734, increase: 282, last: 20 },
  },
  {
    songId: "H02v7OU9Rtg",
    title: "타상연화",
    artist: "릴파, 릭파",
    remix: "",
    reaction: "",
    date: 230401,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 1322074, increase: 276, last: 30 },
  },
  {
    songId: "--Go33WYnqw",
    title: "DAYBREAK FRONTLINE",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 200314,
    start: 0,
    end: 213,
    like: 0,
    hourly: { views: 4589613, increase: 274, last: 17 },
  },
  {
    songId: "YmELthNomns",
    title: "맘가는대로 (ft. 고세구)",
    artist: "세새한 캘리퍼스",
    remix: "",
    reaction: "",
    date: 220918,
    start: 0,
    end: 222,
    like: 0,
    hourly: { views: 5127772, increase: 272, last: 19 },
  },
  {
    songId: "5tGwnxu8NIw",
    title: "Gaea.Zero",
    artist: "릴파",
    remix: "",
    reaction: "",
    date: 230615,
    start: 0,
    end: 206,
    like: 0,
    hourly: { views: 261817, increase: 262, last: 35 },
  },
  {
    songId: "qZi1Xh0_8q4",
    title: "긍지높은 아이돌",
    artist: "고세구",
    remix: "",
    reaction: "",
    date: 221203,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 3041404, increase: 261, last: 24 },
  },
  {
    songId: "J7CAt4CeLtE",
    title: "징무라이스 Remix",
    artist: "징버거",
    remix: "",
    reaction: "",
    date: 230705,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 12015, increase: 253, last: 47 },
  },
  {
    songId: "K-5WdjbCYnk",
    title: "마지막 재회",
    artist: "릴파, 뢴트게늄",
    remix: "",
    reaction: "",
    date: 220605,
    start: 0,
    end: 254,
    like: 0,
    hourly: { views: 6291128, increase: 249, last: 26 },
  },
  {
    songId: "Ozpfl_7_nwc",
    title: "추격자 (The Chaser)",
    artist: "GTS",
    remix: "",
    reaction: "",
    date: 230612,
    start: 5,
    end: 0,
    like: 0,
    hourly: { views: 664412, increase: 247, last: 39 },
  },
  {
    songId: "tT-kuonVzfY",
    title: "STAY",
    artist: "징버거",
    remix: "",
    reaction: "",
    date: 230120,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 2667448, increase: 246, last: 28 },
  },
  {
    songId: "JwEEIHzZNuQ",
    title: "Always with you",
    artist: "릴파",
    remix: "",
    reaction: "",
    date: 221209,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 2273590, increase: 234, last: 22 },
  },
  {
    songId: "JY-gJkMuJ94",
    title: "겨울봄",
    artist: "이세계아이돌",
    remix: "",
    reaction: "",
    date: 220311,
    start: 0,
    end: 238,
    like: 0,
    hourly: { views: 6238157, increase: 234, last: 34 },
  },
  {
    songId: "-ZFDUHgF48U",
    title: "SUMMER TIME",
    artist: "하쿠, 왁컬로이두",
    remix: "백수맛팬치",
    reaction: "J4MM1pRikBg",
    date: 220531,
    start: 11,
    end: 256,
    like: 0,
    hourly: { views: 3596598, increase: 233, last: 44 },
  },
  {
    songId: "-in8F0zmLcM",
    title: "God Knows…",
    artist: "아이네",
    remix: "",
    reaction: "",
    date: 211125,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 3789763, increase: 228, last: 40 },
  },
  {
    songId: "1UbyyaDc8x0",
    title: "세계는 사랑에 빠져있어",
    artist: "릴파",
    remix: "",
    reaction: "",
    date: 220214,
    start: 19,
    end: 0,
    like: 0,
    hourly: { views: 4808193, increase: 228, last: 25 },
  },
  {
    songId: "sP0E6y0gWxA",
    title: "Tot Musica",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 230423,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 927714, increase: 216, last: 46 },
  },
  {
    songId: "uG91iq0AzKM",
    title: "홍련화",
    artist: "고세구",
    remix: "",
    reaction: "",
    date: 230222,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 2472709, increase: 209, last: 31 },
  },
  {
    songId: "pl38om066m0",
    title: "전하지 못한 진심",
    artist: "해루석, 아이네, 릴파, 비챤",
    remix: "",
    reaction: "HiLXC6TWE2k",
    date: 220702,
    start: 5,
    end: 246,
    like: 0,
    hourly: { views: 4050882, increase: 205, last: 51 },
  },
  {
    songId: "YZ0xA3LUzNQ",
    title: "ShowDown (ft. 아이네)",
    artist: "밴틀니",
    remix: "",
    reaction: "",
    date: 220918,
    start: 0,
    end: 251,
    like: 0,
    hourly: { views: 4422444, increase: 201, last: 32 },
  },
  {
    songId: "4ZjDoG0bc5Q",
    title: "SATELLITES",
    artist: "릴파",
    remix: "",
    reaction: "",
    date: 230504,
    start: 0,
    end: 230,
    like: 0,
    hourly: { views: 473222, increase: 195, last: 58 },
  },
  {
    songId: "79rDMDll-IY",
    title: "Ballin'",
    artist: "두세븐 일레븐 FC",
    remix: "",
    reaction: "",
    date: 230313,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 1276439, increase: 191, last: 41 },
  },
  {
    songId: "NVns4yRoTlU",
    title: "취기를 빌려",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 220309,
    start: 0,
    end: 0,
    like: 1,
    hourly: { views: 3814437, increase: 191, last: 52 },
  },
  {
    songId: "tGMDqdUOeD8",
    title: "M자 탈모 (ft. 프리터)",
    artist: "소피아, 도파민박사",
    remix: "",
    reaction: "",
    date: 230610,
    start: 8,
    end: 190,
    like: 0,
    hourly: { views: 393986, increase: 186, last: 73 },
  },
  {
    songId: "kra0f71EIgc",
    title: "TOMBOY (ft. 고세구)",
    artist: "징버거",
    remix: "",
    reaction: "",
    date: 220530,
    start: 6,
    end: 180,
    like: 0,
    hourly: { views: 4009132, increase: 175, last: 61 },
  },
  {
    songId: "1ePxevNqM2s",
    title: "융터르 (Full Ver.)",
    artist: "왁컬로이두",
    remix: "CLTH",
    reaction: "rmRPfxDlphg",
    date: 230310,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 1905520, increase: 171, last: 38 },
  },
  {
    songId: "tc92ES3R6os",
    title: "봄 사랑 벚꽃 말고",
    artist: "주르르, 주폭소년단",
    remix: "",
    reaction: "",
    date: 230601,
    start: 14,
    end: 210,
    like: 0,
    hourly: { views: 443099, increase: 162, last: 33 },
  },
  {
    songId: "Empfi8q0aas",
    title: "이세돌 사이퍼",
    artist: "이세계아이돌, 뢴트게늄",
    remix: "",
    reaction: "VVITtwPKW-E",
    date: 220423,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 5890913, increase: 161, last: 37 },
  },
  {
    songId: "owlLg3R9u6c",
    title: "How To Love (ft. 징버거)",
    artist: "OYT",
    remix: "",
    reaction: "",
    date: 220918,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 4043850, increase: 159, last: 43 },
  },
  {
    songId: "ZLQc1yuUOAM",
    title: "참새",
    artist: "고세구",
    remix: "",
    reaction: "",
    date: 230329,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 1576346, increase: 156, last: 45 },
  },
  {
    songId: "-pczFfMtWrc",
    title: "귀여워서 미안해",
    artist: "주르르",
    remix: "",
    reaction: "",
    date: 230115,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 1468951, increase: 152, last: 68 },
  },
  {
    songId: "nWJB1U7cQVs",
    title: "Butter (ft. 릴파)",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 220611,
    start: 5,
    end: 168,
    like: 0,
    hourly: { views: 2476722, increase: 150, last: 71 },
  },
  {
    songId: "7IcafhbXprU",
    title: "신호등",
    artist: "아이네",
    remix: "",
    reaction: "",
    date: 220419,
    start: 0,
    end: 229,
    like: 0,
    hourly: { views: 3243816, increase: 148, last: 67 },
  },
  {
    songId: "VcvMQ9MZhF8",
    title: "But You Want More",
    artist: "이세계아이돌",
    remix: "",
    reaction: "5ezxTdrpksk",
    date: 220215,
    start: 0,
    end: 197,
    like: 0,
    hourly: { views: 3379817, increase: 148, last: 76 },
  },
  {
    songId: "IzrIYIqlBnA",
    title: "피날레 (ft. 릴파)",
    artist: "레이디버그",
    remix: "",
    reaction: "",
    date: 220918,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 2973596, increase: 148, last: 53 },
  },
  {
    songId: "OTkFJyn4mvc",
    title: "투니버스 메들리",
    artist: "이세계아이돌",
    remix: "",
    reaction: "",
    date: 211205,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 4654979, increase: 148, last: 77 },
  },
  {
    songId: "FeXN3_ub3oQ",
    title: "별빛 등대의 섬",
    artist: "징버거",
    remix: "",
    reaction: "",
    date: 230331,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 801051, increase: 147, last: 74 },
  },
  {
    songId: "YZoeO3T7hsc",
    title: "부엉이",
    artist: "아이네",
    remix: "",
    reaction: "",
    date: 220223,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 3331584, increase: 140, last: 48 },
  },
  {
    songId: "fzHJxq37cqI",
    title: "사랑은 은하수 다방에서 (Love in the Milky Way Cafe)",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 220430,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 2694753, increase: 139, last: 50 },
  },
  {
    songId: "Brf3LWwNVTk",
    title: "LOVE DIVE",
    artist: "이세계아이돌",
    remix: "",
    reaction: "",
    date: 220904,
    start: 0,
    end: 174,
    like: 0,
    hourly: { views: 3988389, increase: 134, last: 42 },
  },
  {
    songId: "X7cO4xQ5Gqs",
    title: "M@STERPIECE",
    artist: "주르르",
    remix: "",
    reaction: "",
    date: 220507,
    start: 0,
    end: 340,
    like: 0,
    hourly: { views: 2439822, increase: 134, last: 82 },
  },
  {
    songId: "Gce2fYnlw0w",
    title: "Re: Dial (ft. 왁컬로이두)",
    artist: "하쿠",
    remix: "백수맛팬치",
    reaction: "kjCtdSXScBo",
    date: 230130,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 1224632, increase: 131, last: 116 },
  },
  {
    songId: "_OsnBqrh6yg",
    title: "어푸",
    artist: "주르르",
    remix: "",
    reaction: "",
    date: 221023,
    start: 0,
    end: 199,
    like: 0,
    hourly: { views: 2323358, increase: 127, last: 63 },
  },
  {
    songId: "8QRrNxCfXh8",
    title: "나의 청춘들에게 (ft. 곽춘식)",
    artist: "도파민박사",
    remix: "",
    reaction: "vGW0UcOKCVQ",
    date: 230423,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 741388, increase: 124, last: 78 },
  },
  {
    songId: "C6ROi2MySL8",
    title: "HEADLINE (헤드라인)",
    artist: "해루석, 곽춘식, 히키킹",
    remix: "",
    reaction: "JepqpVkDhEY",
    date: 221102,
    start: 0,
    end: 158,
    like: 0,
    hourly: { views: 2152762, increase: 123, last: 49 },
  },
  {
    songId: "E90xc5oxUDg",
    title: "에어컨 키면 춥고 끄면 덥고 #Shorts",
    artist: "아이네",
    remix: "",
    reaction: "",
    date: 230626,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 222422, increase: 123, last: 62 },
  },
  {
    songId: "dliS7ToHvzY",
    title: "Crescendo",
    artist: "곽춘식, 하쿠",
    remix: "",
    reaction: "Rua6S5sj_04",
    date: 230528,
    start: 7,
    end: 169,
    like: 0,
    hourly: { views: 394016, increase: 122, last: 96 },
  },
  {
    songId: "KyKATvL6f2w",
    title: "오네가이 머슬 (ft. 남도형)",
    artist: "고도비만",
    remix: "",
    reaction: "x1CzIlIwP0Y",
    date: 230511,
    start: 6,
    end: 228,
    like: 0,
    hourly: { views: 885696, increase: 122, last: 83 },
  },
  {
    songId: "rFxJjpSeXHI",
    title: "SCIENTIST (ft. 아이네)",
    artist: "주르르",
    remix: "",
    reaction: "",
    date: 220314,
    start: 0,
    end: 197,
    like: 0,
    hourly: { views: 5297133, increase: 120, last: 60 },
  },
  {
    songId: "YwQkPlFlOJQ",
    title: "STARLIGHT (ft. 주르르)",
    artist: "하와유",
    remix: "",
    reaction: "",
    date: 220918,
    start: 5,
    end: 233,
    like: 0,
    hourly: { views: 2719402, increase: 120, last: 75 },
  },
  {
    songId: "P-wOE92vfyk",
    title: "유령도쿄",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 210116,
    start: 0,
    end: 201,
    like: 0,
    hourly: { views: 2305790, increase: 117, last: 55 },
  },
  {
    songId: "G0g3d6b5CZM",
    title: "Choose me",
    artist: "주르르, 뢴트게늄, 징버거",
    remix: "",
    reaction: "",
    date: 220128,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 3180221, increase: 117, last: 69 },
  },
  {
    songId: "pDzR-0_zwXk",
    title: "잠깐나올래",
    artist: "해루석",
    remix: "",
    reaction: "",
    date: 230327,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 1636534, increase: 112, last: 54 },
  },
  {
    songId: "xs4d6QjY03w",
    title: "Da Capo",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 230306,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 756273, increase: 111, last: 87 },
  },
  {
    songId: "6l6nqQbmMsY",
    title: "그 녀석",
    artist: "독고혜지, 비밀소녀, 하쿠",
    remix: "",
    reaction: "",
    date: 230529,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 494344, increase: 108, last: 81 },
  },
  {
    songId: "1f0KwkGLXr0",
    title: "Rumor",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 200222,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 1401955, increase: 103, last: 70 },
  },
  {
    songId: "7D8wnXs4zSU",
    title: "Fire Again",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 220902,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 1387645, increase: 103, last: 88 },
  },
  {
    songId: "bwgR3hAR7nQ",
    title: "Popular",
    artist: "아이네",
    remix: "",
    reaction: "",
    date: 230215,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 717798, increase: 102, last: 93 },
  },
  {
    songId: "3XoZ8MsphNw",
    title: "미리 메리 크리스마스 (ft. 천양)",
    artist: "징버거, 주르르, 비챤",
    remix: "",
    reaction: "",
    date: 221225,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 903963, increase: 95, last: 105 },
  },
  {
    songId: "aLB9ttASxPI",
    title: "메리 크리",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 230116,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 716667, increase: 95, last: 94 },
  },
  {
    songId: "xAr7ADitQU0",
    title: "강풍 올백머리",
    artist: "하쿠",
    remix: "",
    reaction: "",
    date: 230420,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 1110995, increase: 94, last: 90 },
  },
  {
    songId: "Q14LWSckkPg",
    title: "Lemon",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 201014,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 1026547, increase: 94, last: 80 },
  },
  {
    songId: "AA8acCRSvEA",
    title: "버스 안에서",
    artist: "오이쿤(주폭), 윤대대(주폭), 코코미(지하돌), 배춘희(지하돌)",
    remix: "",
    reaction: "v1IpzIezRxY",
    date: 230630,
    start: 41,
    end: 230,
    like: 0,
    hourly: { views: 51174, increase: 93, last: 84 },
  },
  {
    songId: "8tJb1YlMHfA",
    title: "너로피어오라 (Flowering)",
    artist: "릴파",
    remix: "",
    reaction: "",
    date: 220331,
    start: 0,
    end: 224,
    like: 0,
    hourly: { views: 2524858, increase: 92, last: 59 },
  },
  {
    songId: "GU_uQm39nfM",
    title: "NIGHT DANCER",
    artist: "권민",
    remix: "",
    reaction: "",
    date: 230527,
    start: 7,
    end: 0,
    like: 0,
    hourly: { views: 673616, increase: 91, last: 57 },
  },
  {
    songId: "TYB9ScXvq34",
    title: "우마뾰이 전설",
    artist: "이세계아이돌",
    remix: "",
    reaction: "",
    date: 220823,
    start: 0,
    end: 135,
    like: 0,
    hourly: { views: 2878413, increase: 87, last: 72 },
  },
  {
    songId: "xBiOm4-fkU4",
    title: "Henceforth",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 200703,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 1853586, increase: 86, last: 66 },
  },
  {
    songId: "Mn5ZwEFKBc4",
    title: "봄날",
    artist: "왁타버스",
    remix: "",
    reaction: "1z99VbWPZUY",
    date: 220408,
    start: 25,
    end: 315,
    like: 0,
    hourly: { views: 2109041, increase: 86, last: 98 },
  },
  {
    songId: "fU8picIMbSk",
    title: "장난기 기능",
    artist: "이세계아이돌",
    remix: "",
    reaction: "_kzOXi3cjPY",
    date: 210913,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 3861331, increase: 85, last: 100 },
  },
  {
    songId: "M7CvycHOizg",
    title: "Mood Indigo",
    artist: "비밀소녀, 해루석",
    remix: "",
    reaction: "Xe_xjzyF89M",
    date: 220403,
    start: 0,
    end: 221,
    like: 0,
    hourly: { views: 1570782, increase: 85, last: 121 },
  },
  {
    songId: "9soAWkBqXyw",
    title: "BOY",
    artist: "짬통스",
    remix: "",
    reaction: "LnGSrNKCPmM",
    date: 230405,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 991519, increase: 85, last: 56 },
  },
  {
    songId: "sVydSseSOCQ",
    title: "오르막길",
    artist: "뢴트게늄, 해루석",
    remix: "",
    reaction: "",
    date: 221208,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 1510659, increase: 83, last: 79 },
  },
  {
    songId: "w1kTv8iUx9w",
    title: "사랑을 전하고 싶다던가",
    artist: "비챤",
    remix: "",
    reaction: "jW03jp-YWwc",
    date: 200413,
    start: 0,
    end: 231,
    like: 0,
    hourly: { views: 1353987, increase: 83, last: 65 },
  },
  {
    songId: "SAJrAQGvOHE",
    title: "Bom (나만, 봄)",
    artist: "고세구",
    remix: "",
    reaction: "",
    date: 220522,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 2745325, increase: 83, last: 95 },
  },
  {
    songId: "7wubxhtPKQE",
    title: "목요일 밤",
    artist: "징버거, 릴파, 뢴트게늄, 풍신",
    remix: "",
    reaction: "Mz2rceinKjQ",
    date: 221117,
    start: 0,
    end: 220,
    like: 0,
    hourly: { views: 1062219, increase: 82, last: 112 },
  },
  {
    songId: "4dsMLdXpDOY",
    title: "로키 (ROKI)",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 180326,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 2031781, increase: 81, last: 64 },
  },
  {
    songId: "jzt_aR_PSGo",
    title: "Left and Right",
    artist: "비밀소녀, 해루석",
    remix: "",
    reaction: "",
    date: 221014,
    start: 0,
    end: 153,
    like: 0,
    hourly: { views: 1537732, increase: 81, last: 104 },
  },
  {
    songId: "4xZYZTWH0qk",
    title: "고양이",
    artist: "아이네, 비챤",
    remix: "",
    reaction: "",
    date: 211113,
    start: 0,
    end: 0,
    like: 0,
    hourly: { views: 1495782, increase: 80, last: 114 },
  },
  {
    songId: "lQIdaZgK56A",
    title: "eight",
    artist: "징버거, 비밀소녀, 천양",
    remix: "",
    reaction: "cDZO3EbqBkk",
    date: 220228,
    start: 0,
    end: 170,
    like: 0,
    hourly: { views: 2193684, increase: 80, last: 122 },
  },
];

export const recommended = [
  {
    key: "best",
    title: "역대 왁뮤 1위",
    public: true,
    createAt: 1686382026000,
    image: {
      round: 1,
      square: 1,
    },
    songs: [],
  },
  {
    key: "official",
    title: "ALL : MUSIC",
    public: true,
    createAt: 1686382026000,
    image: {
      round: 1,
      square: 1,
    },
    songs: [],
  },
  {
    key: "gomemsong",
    title: "가요제&학예회",
    public: true,
    createAt: 1675316173132,
    image: {
      round: 2,
      square: 2,
    },
    songs: [],
  },
  {
    key: "competition",
    title: "연말공모전",
    public: true,
    createAt: 1675316173132,
    image: {
      round: 2,
      square: 2,
    },
    songs: [],
  },
  {
    key: "carol",
    title: "캐롤",
    public: true,
    createAt: 1675316173132,
    image: {
      round: 2,
      square: 2,
    },
    songs: [],
  },
  {
    key: "hiphop",
    title: "힙합 SWAG",
    public: true,
    createAt: 1675316173132,
    image: {
      round: 2,
      square: 2,
    },
    songs: [],
  },
  {
    key: "worksong",
    title: "노동요",
    public: true,
    createAt: 1675316173132,
    image: {
      round: 2,
      square: 2,
    },
    songs: [],
  },
  {
    key: "confidence",
    title: "자신감 충전",
    public: true,
    createAt: 1686382026000,
    image: {
      round: 1,
      square: 1,
    },
    songs: [],
  },
];

export const songList: SongsSearchResponse = {
  song: [
    {
      songId: "K8WC6uWyC9I",
      title: "그냥 살아! (ft. 비챤)",
      artist: "김피탕앤짬뽕",
      remix: "",
      reaction: "",
      date: 220918,
      start: 16,
      end: 0,
      like: 0,
      total: { views: 7952476, increase: 319, last: 4 },
    },
    {
      songId: "TriBGtGgnuI",
      title: "기어와라 망냥냥양",
      artist: "비챤",
      remix: "큐컴버",
      reaction: "SlFfF_jdjUY",
      date: 220606,
      start: 0,
      end: 78,
      like: 0,
      total: { views: 634003, increase: 2, last: 228 },
    },
    {
      songId: "2kYrlukIXm4",
      title: "망냥냥캣 #Shorts",
      artist: "비챤",
      remix: "위윌왁휴",
      reaction: "",
      date: 220806,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 237721, increase: 0, last: 465 },
    },
    {
      songId: "Vt0lSTxSjaw",
      title:
        "Whatever (ft. 율음, 키드밀리, 그냥노창, The Quiett, Raf Sandou) (doubling. 히키킹)",
      artist: "sAewoo",
      remix: "",
      reaction: "",
      date: 220418,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 146842, increase: 0, last: 598 },
    },
    {
      songId: "WQApknUVDDg",
      title: "그냥 살아! (ft. 왁컬로이두)",
      artist: "비챤, 아컬로이드, 고컬로이드",
      remix: "꽃세계",
      reaction: "V92zyZobGLY",
      date: 221005,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 103967, increase: 0, last: 710 },
    },
    {
      songId: "oz5AoL3ovfA",
      title: "그냥 살아!&맘가는대로 (Live Ver.)",
      artist: "주르르",
      remix: "",
      reaction: "",
      date: 221218,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 63102, increase: 0, last: 851 },
    },
    {
      songId: "P8o69SEkBv4",
      title: "그냥 살아! (8bit Remix)",
      artist: "김피탕앤짬뽕",
      remix: "OVERSANS",
      reaction: "",
      date: 221014,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 10217, increase: 0, last: 1392 },
    },
    {
      songId: "SVbkvrB6Kvo",
      title: "비챤이 우와하고 망냥냥이 모찌모찌",
      artist: "비챤",
      remix: "Recci",
      reaction: "",
      date: 230219,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 7272, increase: 0, last: 1519 },
    },
    {
      songId: "P38Fs8bPPK8",
      title: "냥뇽갈비 #Shorts",
      artist: "징버거",
      remix: "kingbadnae",
      reaction: "",
      date: 230317,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 4698, increase: 0, last: 1635 },
    },
    {
      songId: "_Ulq7vQePSU",
      title: "그냥 살아",
      artist: "클리보",
      remix: "",
      reaction: "",
      date: 221222,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 4658, increase: 0, last: 1640 },
    },
    {
      songId: "kxufR-QnvkI",
      title: "너는 그냥 가만히 있으면 돼",
      artist: "왁컬로이두",
      remix: "해원이",
      reaction: "",
      date: 230129,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 1369, increase: 0, last: 1875 },
    },
  ],
  artist: [
    {
      songId: "NVm8Uzai9HY",
      title: "없는계절 (ft. 아이네, 씨잼, 윤훼이)",
      artist: "그냥노창",
      remix: "",
      reaction: "",
      date: 220402,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 343114, increase: 2, last: 357 },
    },
    {
      songId: "I92GTsOVG7E",
      title: "Whatever 가녹음 실패작 (doubling. 히키킹)",
      artist: "그냥노창",
      remix: "",
      reaction: "",
      date: 220418,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 321462, increase: 6, last: 378 },
    },
    {
      songId: "XFh92D_F03w",
      title: "Oh wow!",
      artist: "챤컬로이드, 망냥냥",
      remix: "큐컴버",
      reaction: "",
      date: 230622,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 33193, increase: 27, last: 1033 },
    },
  ],
  remix: [
    {
      songId: "9JzFQ_nJElk",
      title: "되감난 고장기버튼 (ft. 우왁굳)",
      artist: "이세계아이돌, 히키킹",
      remix: "그냥노창",
      reaction: "",
      date: 211229,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 98753, increase: 1, last: 723 },
    },
    {
      songId: "BxJFFFEQC48",
      title: "TRUE LOVER Remix",
      artist: "이세계오빠들",
      remix: "그냥노창",
      reaction: "",
      date: 221014,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 33394, increase: 0, last: 1032 },
    },
    {
      songId: "OCimjWl9d8I",
      title: "겨울봄 Remix",
      artist: "이세계아이돌",
      remix: "그냥노창",
      reaction: "",
      date: 220813,
      start: 0,
      end: 108,
      like: 0,
      total: { views: 26135, increase: 1, last: 1090 },
    },
  ],
};

export const profileList = [
  {
    type: "panchi",
    version: 2,
  },
  {
    type: "ifari",
    version: 2,
  },
  {
    type: "dulgi",
    version: 2,
  },
  {
    type: "bat",
    version: 2,
  },
  {
    type: "segyun",
    version: 2,
  },
  {
    type: "gorani",
    version: 2,
  },
  {
    type: "jupock",
    version: 2,
  },
  {
    type: "ddong",
    version: 2,
  },
];

const myListSongs = [
  {
    songId: "QgMFpuos4Rg",
    title: "LOCKDOWN",
    artist: "이세계아이돌",
    remix: "",
    reaction: "",
    date: 230622,
    start: 0,
    end: 0,
    like: 1,
    total: { views: 3004739, increase: 2894, last: 1 },
  },
  {
    songId: "SXE-gIU3yJs",
    title: "고멤가요제 MASHUP",
    artist: "아이네",
    remix: "",
    reaction: "",
    date: 221201,
    start: 0,
    end: 0,
    like: 0,
    total: { views: 5105546, increase: 740, last: 3 },
  },
  {
    songId: "iLXmqg_HHRA",
    title: "스물셋",
    artist: "비챤",
    remix: "",
    reaction: "5pIR8SGmgkg",
    date: 230617,
    start: 0,
    end: 192,
    like: 0,
    total: { views: 883975, increase: 710, last: 2 },
  },
  {
    songId: "fgSXAKsq-Vo",
    title: "리와인드 (RE:WIND)",
    artist: "이세계아이돌",
    remix: "",
    reaction: "",
    date: 211222,
    start: 0,
    end: 270,
    like: 0,
    total: { views: 15676550, increase: 654, last: 4 },
  },
  {
    songId: "aK76gQHIm04",
    title: "징버거 궁시렁 Remix",
    artist: "징버거",
    remix: "레이지스피크",
    reaction: "zxVzfCawDyE",
    date: 221220,
    start: 0,
    end: 0,
    like: 0,
    total: { views: 3028840, increase: 578, last: 5 },
  },
  {
    songId: "IK-z7xhiKB0",
    title: "PINK VENOM",
    artist: "저세계아이돌",
    remix: "",
    reaction: "",
    date: 230702,
    start: 0,
    end: 186,
    like: 0,
    total: { views: 283411, increase: 558, last: 6 },
  },
  {
    songId: "EA_gei4Fcxk",
    title: "Hot Summer",
    artist: "러브 미쓰 피쓰",
    remix: "",
    reaction: "",
    date: 230612,
    start: 0,
    end: 229,
    like: 0,
    total: { views: 1300552, increase: 479, last: 14 },
  },
  {
    songId: "DPEtmqvaKqY",
    title: "팬서비스",
    artist: "고세구",
    remix: "",
    reaction: "",
    date: 220111,
    start: 0,
    end: 0,
    like: 0,
    total: { views: 9540461, increase: 462, last: 8 },
  },
  {
    songId: "qunpFTI90sU",
    title: "강풍 올백머리",
    artist: "징버거",
    remix: "",
    reaction: "JOWZiZWNjHg",
    date: 230426,
    start: 0,
    end: 0,
    like: 0,
    total: { views: 2321698, increase: 462, last: 16 },
  },
  {
    songId: "gEKKOrvh92Y",
    title: "아이돌 #Shorts",
    artist: "징버거",
    remix: "",
    reaction: "",
    date: 230612,
    start: 0,
    end: 0,
    like: 0,
    total: { views: 2545825, increase: 449, last: 13 },
  },
  {
    songId: "l8e1Byk1Dx0",
    title: "TRUE LOVER (ft. 행주)",
    artist: "이세계오빠들",
    remix: "",
    reaction: "",
    date: 220918,
    start: 0,
    end: 200,
    like: 0,
    total: { views: 8805280, increase: 446, last: 7 },
  },
  {
    songId: "_lwD3ILdKi0",
    title: "무희",
    artist: "뢴트게늄",
    remix: "",
    reaction: "",
    date: 230225,
    start: 0,
    end: 0,
    like: 0,
    total: { views: 2979593, increase: 444, last: 9 },
  },
  {
    songId: "6hEvgKL0ClA",
    title: "Promise",
    artist: "릴파",
    remix: "",
    reaction: "",
    date: 211229,
    start: 0,
    end: 243,
    like: 0,
    total: { views: 7047127, increase: 440, last: 10 },
  },
  {
    songId: "mqcGI5QGmzk",
    title: "계절범죄",
    artist: "이노리(지하돌), 흰젓가락(주폭), 우앵두(지하돌)",
    remix: "",
    reaction: "CN8cZabPVgM",
    date: 230630,
    start: 0,
    end: 229,
    like: 0,
    total: { views: 118503, increase: 430, last: 15 },
  },
  {
    songId: "S2I6tRQtR58",
    title: "Grrr",
    artist: "왁컬로이두",
    remix: "큐컴버",
    reaction: "beBJf_eifnY",
    date: 230702,
    start: 0,
    end: 0,
    like: 0,
    total: { views: 132930, increase: 422, last: 27 },
  },
  {
    songId: "p9TFQ9ySJLs",
    title: "봄도둑",
    artist: "징버거",
    remix: "",
    reaction: "",
    date: 230430,
    start: 0,
    end: 288,
    like: 0,
    total: { views: 1084810, increase: 402, last: 18 },
  },
  {
    songId: "lLIpFxWtqCQ",
    title:
      "사랑하긴 했었나요 스쳐가는 인연이었나요 짧지않은 우리 함께했던 시간들이 자꾸 내 마음을 가둬두네 (Baby I need you)",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 221216,
    start: 0,
    end: 0,
    like: 0,
    total: { views: 3307240, increase: 371, last: 12 },
  },
  {
    songId: "KjySNSxgg3U",
    title: "저곳으로",
    artist: "징버거",
    remix: "",
    reaction: "GZDoPjRpAoQ",
    date: 230531,
    start: 0,
    end: 0,
    like: 0,
    total: { views: 1632994, increase: 335, last: 11 },
  },
  {
    songId: "eWaBljLkd08",
    title: "Ballin'",
    artist: "징버거",
    remix: "",
    reaction: "",
    date: 230525,
    start: 0,
    end: 0,
    like: 0,
    total: { views: 580998, increase: 333, last: 21 },
  },
  {
    songId: "K8WC6uWyC9I",
    title: "그냥 살아! (ft. 비챤)",
    artist: "김피탕앤짬뽕",
    remix: "",
    reaction: "",
    date: 220918,
    start: 16,
    end: 0,
    like: 0,
    total: { views: 7952476, increase: 319, last: 23 },
  },
];

export const dumyListItem = {
  key: "key1",
  index: -1,
  title: "리스트제목열두글자자자자",
  createAt: 1684622625731,
  user: {
    displayName: "이름",
    profile: {
      type: "gorani",
      version: 2,
    },
  },
  image: {
    name: "1",
    version: 11,
  },
  songs: myListSongs,
};

export const myList = [
  {
    key: "key1",
    title: "플레이리스트 1",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 1,
    },
    songs: myListSongs,
  },
  {
    key: "key2",
    title: "플레이리스트 2",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 7,
    },
    songs: myListSongs,
  },
  {
    key: "key3",
    title: "플레이리스트 3",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 3,
    },
    songs: myListSongs,
  },
  {
    key: "key4",
    title: "플레이리스트 4",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 11,
    },
    songs: myListSongs,
  },
  {
    key: "key5",
    title: "플레이리스트 5",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 5,
    },
    songs: myListSongs,
  },
  {
    key: "key6",
    title: "플레이리스트 6",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 6,
    },
    songs: myListSongs,
  },
  {
    key: "key7",
    title: "플레이리스트 7",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 7,
    },
    songs: myListSongs,
  },
  {
    key: "key8",
    title: "플레이리스트 8",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 8,
    },
    songs: myListSongs,
  },
  {
    key: "key9",
    title: "플레이리스트 9",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 9,
    },
    songs: myListSongs,
  },
  {
    key: "key10",
    title: "플레이리스트 10",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 10,
    },
    songs: myListSongs,
  },
  {
    key: "key11",
    title: "플레이리스트 11",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 11,
    },
    songs: myListSongs,
  },
];

export const lyrics = [
  {
    identifier: "1",
    start: 17.17,
    end: 19.9,
    text: "기억나 우리 처음 만난 날",
    styles: "",
  },
  {
    identifier: "2",
    start: 19.9,
    end: 23.77,
    text: "내게 오던 너의 그 미소가",
    styles: "",
  },
  {
    identifier: "3",
    start: 23.77,
    end: 26.99,
    text: "마치 날 알고 있던 것처럼",
    styles: "",
  },
  {
    identifier: "4",
    start: 26.99,
    end: 30.77,
    text: "매일 스쳐 지나가던 바람처럼",
    styles: "",
  },
  {
    identifier: "5",
    start: 30.77,
    end: 34.1,
    text: "가끔은 우리 사이가 멀어질까",
    styles: "",
  },
  {
    identifier: "6",
    start: 34.1,
    end: 37.78,
    text: "혼자 남아버리는 상상을 해 oh",
    styles: "",
  },
  {
    identifier: "7",
    start: 37.78,
    end: 40.93,
    text: "이런 나를 잡아줘 우리 처음",
    styles: "",
  },
  {
    identifier: "8",
    start: 40.93,
    end: 46.06,
    text: "만난 날처럼 내가 너를 꼭 찾을 수 있게",
    styles: "",
  },
  {
    identifier: "9",
    start: 46.06,
    end: 49.7,
    text: "늘 꿈에서만 그리던",
    styles: "",
  },
  {
    identifier: "10",
    start: 49.7,
    end: 52.93,
    text: "너와 함께 할 모든 날들이",
    styles: "",
  },
  {
    identifier: "11",
    start: 52.93,
    end: 55.97,
    text: "더 희미해지기 전에",
    styles: "",
  },
  {
    identifier: "12",
    start: 55.97,
    end: 57.9,
    text: "나 시간이 없어",
    styles: "",
  },
  {
    identifier: "13",
    start: 57.9,
    end: 61.51,
    text: "지금 닿을 수는 없는 거리 일지라도",
    styles: "",
  },
  {
    identifier: "14",
    start: 61.51,
    end: 64.98,
    text: "꼭 너와 함께 있다는 기분이 들어",
    styles: "",
  },
  {
    identifier: "15",
    start: 64.98,
    end: 66.9,
    text: "널 주저했던 걸음, 마음. 나는",
    styles: "",
  },
  {
    identifier: "16",
    start: 66.9,
    end: 69.7,
    text: "왜 이리 바보 같은 지",
    styles: "",
  },
  {
    identifier: "17",
    start: 69.7,
    end: 71.85,
    text: "자신이 없어",
    styles: "",
  },
  {
    identifier: "18",
    start: 71.85,
    end: 78.19,
    text: "늘 같은 곳을 바라보던 너의 그 눈이 좋아",
    styles: "",
  },
  {
    identifier: "19",
    start: 78.19,
    end: 83.7,
    text: "변한 세상에서 너만은 그대로 있어줘",
    styles: "",
  },
  {
    identifier: "20",
    start: 83.7,
    end: 85.56,
    text: "you're my sunshine",
    styles: "",
  },
  {
    identifier: "21",
    start: 85.56,
    end: 91.47,
    text: "늘 같은 곳을 헤매이던 너와 내 시간 속에",
    styles: "",
  },
  {
    identifier: "22",
    start: 91.47,
    end: 95.37,
    text: "날 잊어버린다 해도",
    styles: "",
  },
  {
    identifier: "23",
    start: 95.37,
    end: 114.86,
    text: "다시 한번 너를 만나러 갈 테니까",
    styles: "",
  },
  {
    identifier: "24",
    start: 114.86,
    end: 117.9,
    text: "조금씩 가까워지고 있어",
    styles: "",
  },
  {
    identifier: "25",
    start: 117.9,
    end: 121.6,
    text: "느껴지니 보이진 않아도",
    styles: "",
  },
  {
    identifier: "26",
    start: 121.6,
    end: 124.77,
    text: "한 조각 마지막 퍼즐처럼",
    styles: "",
  },
  {
    identifier: "27",
    start: 124.77,
    end: 128.61,
    text: "너 하나로 내 세상이 맞물려가",
    styles: "",
  },
  {
    identifier: "28",
    start: 128.61,
    end: 131.91,
    text: "어쩌면 넌 사라질 무지개처럼",
    styles: "",
  },
  {
    identifier: "29",
    start: 131.91,
    end: 135.48,
    text: "날 두고 떠날지도 모르지만",
    styles: "",
  },
  {
    identifier: "30",
    start: 135.48,
    end: 138.68,
    text: "이런 나를 잡아줘 우리 처음",
    styles: "",
  },
  {
    identifier: "31",
    start: 138.68,
    end: 143.76,
    text: "만난 날처럼 내가 너를 꼭 잡을 수 있게",
    styles: "",
  },
  {
    identifier: "32",
    start: 143.76,
    end: 147.49,
    text: "늘 꿈에서만 그리던",
    styles: "",
  },
  {
    identifier: "33",
    start: 147.49,
    end: 150.66,
    text: "너와 함께 할 모든 날들이",
    styles: "",
  },
  {
    identifier: "34",
    start: 150.66,
    end: 154.03,
    text: "더 희미해지기 전에",
    styles: "",
  },
  {
    identifier: "35",
    start: 154.03,
    end: 155.63,
    text: "나 시간이 없어",
    styles: "",
  },
  {
    identifier: "36",
    start: 155.63,
    end: 159.21,
    text: "지금 닿을 수는 없는 거리 일지라도",
    styles: "",
  },
  {
    identifier: "37",
    start: 159.21,
    end: 162.67000000000002,
    text: "꼭 너와 함께 있다는 기분이 들어",
    styles: "",
  },
  {
    identifier: "38",
    start: 162.67000000000002,
    end: 164.82999999999998,
    text: "날 주저했던 걸음, 마음. 너의",
    styles: "",
  },
  {
    identifier: "39",
    start: 164.82999999999998,
    end: 167.78,
    text: "세상이 끝난다 해도",
    styles: "",
  },
  {
    identifier: "40",
    start: 167.78,
    end: 169.32,
    text: "기다릴 거야",
    styles: "",
  },
  {
    identifier: "41",
    start: 169.32,
    end: 175.89,
    text: "차원을 넘어 너에게 달려가고 있어 지금",
    styles: "",
  },
  {
    identifier: "42",
    start: 175.89,
    end: 181.49,
    text: "내 심장소리가 터질 것만 같아 들어봐",
    styles: "",
  },
  {
    identifier: "43",
    start: 181.49,
    end: 183.26,
    text: "기억해 줘",
    styles: "",
  },
  {
    identifier: "44",
    start: 183.26,
    end: 189.27,
    text: "이 세상 속에 멈춰있는 너와 내 시간 속에",
    styles: "",
  },
  {
    identifier: "45",
    start: 189.27,
    end: 193.01,
    text: "어쩌면 이건 우리의",
    styles: "",
  },
  {
    identifier: "46",
    start: 193.01,
    end: 196.44,
    text: "처음이자 마지막 사랑",
    styles: "",
  },
  {
    identifier: "47",
    start: 196.44,
    end: 209.02,
    text: "일테니까",
    styles: "",
  },
  {
    identifier: "48",
    start: 209.02,
    end: 210.72,
    text: "기억해 줘",
    styles: "",
  },
  {
    identifier: "49",
    start: 210.72,
    end: 216.67000000000002,
    text: "이 꿈속 너와 함께했던 시간은 진짜일까",
    styles: "",
  },
  {
    identifier: "50",
    start: 216.67000000000002,
    end: 220.63,
    text: "늘 간직하던 약속들 그대로",
    styles: "",
  },
  {
    identifier: "51",
    start: 220.63,
    end: 236.15,
    text: "just waiting for you",
    styles: "",
  },
  {
    identifier: "52",
    start: 236.15,
    end: 238.18,
    text: "you're my sunshine",
    styles: "",
  },
  {
    identifier: "53",
    start: 238.18,
    end: 244.16,
    text: "이 세상 속에 멈춰있는 너와 내 시간 속에",
    styles: "",
  },
  {
    identifier: "54",
    start: 244.16,
    end: 247.99,
    text: "어쩌면 이건 우리의",
    styles: "",
  },
  {
    identifier: "55",
    start: 247.99,
    end: 253.13,
    text: "처음이자 마지막 사랑 일 테니까",
    styles: "",
  },
];
