import { SongsSearchResponse } from "@templates/search";

export const chartUpdated = "1688630567";

export const faq = {
  category: [
    { type: "qna", category: "전체" },
    { type: "qna", category: "기타" },
    { type: "qna", category: "리스트" },
    { type: "qna", category: "회원" },
    { type: "qna", category: "플레이어" },
  ],
  article: [
    {
      question: "왁뮤에서 노래를 들어도 유튜브 조회수에 반영이 되나요?",
      description:
        "반영됩니다. \n왁타버스 뮤직은 유튜브 기반 플레이어를 사용하여 재생되는 모든 음악이 조회수로 집계됩니다.",
      createAt: 1687696656,
      category: { type: "qna", category: "기타" },
    },
    {
      question: "나만의 플레이리스트 만들 수 있나요?",
      description:
        "만들 수 있습니다.\n로그인 후 보관함에서 '리스트 만들기'를 선택하면 생성이 가능합니다. 생성된 리스트는 앱과 연동이 됩니다.",
      createAt: 1687697114,
      category: { type: "qna", category: "리스트" },
    },
    {
      question: "회원탈퇴는 어떻게 할 수 있나요?",
      description:
        "'보관함' > 오른쪽 상단 '건의사항' > 오른쪽 상단 '회원탈퇴' 버튼을 통해 탈퇴할 수 있습니다.",
      createAt: 1687697156,
      category: { type: "qna", category: "회원" },
    },
    {
      question: "프로필을 편집할 수 있나요?",
      description:
        "‘보관함’ > 왼쪽 상단 ‘프로필’을 선택하면 프로필 사진과 닉네임 모두 편집 가능합니다.",
      createAt: 1687697201,
      category: { type: "qna", category: "회원" },
    },
    {
      question: "데이터 소모량이 어떻게 되나요?",
      description: "유튜브 영상과 비슷합니다.",
      createAt: 1687697242,
      category: { type: "qna", category: "기타" },
    },
    {
      question: "왁뮤목록에 없는 노래를 추가하려고 하는데 어떻게 해야 하나요?",
      description: "‘보관함’ > ‘건의사항’ > ‘문의하기’를 이용해주세요.",
      createAt: 1687697306,
      category: { type: "qna", category: "기타" },
    },
    {
      question: "썸네일 말고 영상이 나오게는 할 수 없나요?",
      description:
        "영상이 플레이되면 기능에 제약이 생기는 문제가 많아서 썸네일만 표시되도록 조정했습니다.",
      createAt: 1687697382,
      category: { type: "qna", category: "플레이어" },
    },
    {
      question: "특정 노래들이 다른 노래에 비해서 소리가 너무 작아요.",
      description:
        "유튜브에서 그대로 가져오기 때문에 원본이 소리가 작으면 작게 들립니다.",
      createAt: 1687697451,
      category: { type: "qna", category: "플레이어" },
    },
    {
      question: "가사가 아직 안나오는 곡들이 있어요.",
      description:
        "작업 중입니다. 가내수공업으로 직접 제작 중이니 이해 부탁드립니다.",
      createAt: 1687697499,
      category: { type: "qna", category: "기타" },
    },
    {
      question: "PC와 모바일이 연동이 되나요?",
      description:
        "계정이 연동되어 있어 내 리스트, 좋아요 등의 기능을 두 플랫폼 모두 사용하실 수 있습니다.",
      createAt: 1687697585,
      category: { type: "qna", category: "기타" },
    },
    {
      question: "iOS 백그라운드 재생 진입 시 잠시 끊겨요",
      description: "개발자 : “어쩔 수 없음”",
      createAt: 1687697669,
      category: { type: "qna", category: "플레이어" },
    },
    {
      question:
        "블루투스 연결이 끊기면 노래가 일시정지되지 않아서 노래가 나와요. 암살 방지 기능 안되나요?",
      description: "개발자 : “힘든 상황…”",
      createAt: 1687697703,
      category: { type: "qna", category: "기타" },
    },
    {
      question: "버그제보는 아무나 이용 가능한가요?",
      description:
        "네 가능합니다. \n다만 정말 필요할 경우에만 이용 바랍니다. 많은 데이터 이동으로 인한 서버 부담이 이어질 수 있습니다.",
      createAt: 1687697741,
      category: { type: "qna", category: "기타" },
    },
    {
      question: "안드로이드 백그라운드 재생 중 다음 곡으로 넘어가질 않아요",
      description:
        "배터리 절약 옵션과 충돌이 날 수 있습니다.\n'설정 > 애플리케이션 > 왁타버스 뮤직 > 배터리 > 제한 없음' 순서대로 설정 부탁드립니다.",
      createAt: 1689083213,
      category: { type: "qna", category: "플레이어" },
    },
  ],
};

export const userInfo = {
  username: "왁타버스 뮤직",
  via: "카카오톡",
};

export const dummySong = {
  songId: "dummySongId",
  title: "dummy'",
  artist: "dummy",
  remix: "",
  reaction: "",
  date: 230525,
  start: 0,
  end: 0,
  like: 0,
  total: { views: 580998, increase: 333, last: 21 },
};

export const hourlyChart = [
  {
    songId: "XqAKiaxAdu0",
    title: "Give Love",
    artist: "고세구, 왁컬로이두",
    remix: "거시깽",
    reaction: "T-VYpqNIk2U",
    date: 230203,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 104403,
      increase: 7402,
      last: 1,
    },
  },
  {
    songId: "crvPldgKJIo",
    title: "LADY",
    artist: "릴파",
    remix: "",
    reaction: "5KNFd9NOaKU",
    date: 230709,
    start: 10,
    end: 0,
    like: 0,
    hourly: {
      views: 3611514,
      increase: 4671,
      last: 2,
    },
  },
  {
    songId: "QgMFpuos4Rg",
    title: "LOCKDOWN",
    artist: "이세계아이돌",
    remix: "",
    reaction: "",
    date: 230622,
    start: 0,
    end: 0,
    like: 1,
    hourly: {
      views: 4504115,
      increase: 2742,
      last: 3,
    },
  },
  {
    songId: "8KTFf2X-ago",
    title: "Another World",
    artist: "이세계아이돌",
    remix: "",
    reaction: "",
    date: 230721,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 1222458,
      increase: 2212,
      last: 4,
    },
  },
  {
    songId: "_CvJ0Ue-y6M",
    title: "잠깐나올래 (Jazz Ver.)",
    artist: "해루석",
    remix: "",
    reaction: "",
    date: 230802,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 46115,
      increase: 1843,
      last: 6,
    },
  },
  {
    songId: "fgSXAKsq-Vo",
    title: "리와인드 (RE:WIND)",
    artist: "이세계아이돌",
    remix: "",
    reaction: "",
    date: 211222,
    start: 0,
    end: 270,
    like: 0,
    hourly: {
      views: 16138819,
      increase: 1363,
      last: 7,
    },
  },
  {
    songId: "SXE-gIU3yJs",
    title: "고멤가요제 MASHUP",
    artist: "아이네",
    remix: "",
    reaction: "",
    date: 221201,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 5593022,
      increase: 1040,
      last: 8,
    },
  },
  {
    songId: "SdsKPOrDrXo",
    title: "메이크업 (ft. 왁컬로이두)",
    artist: "AI뢴트게늄",
    remix: "큐컴버",
    reaction: "",
    date: 230803,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 11630,
      increase: 1036,
      last: 10,
    },
  },
  {
    songId: "82XRPBUm2y0",
    title: "축복",
    artist: "고세구",
    remix: "",
    reaction: "",
    date: 230802,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 36238,
      increase: 941,
      last: 9,
    },
  },
  {
    songId: "9p4XyIS0nvI",
    title: "Sharks",
    artist: "씹상가이즈",
    remix: "",
    reaction: "gRKE7fTsi9I",
    date: 230712,
    start: 0,
    end: 188,
    like: 0,
    hourly: {
      views: 740136,
      increase: 896,
      last: 12,
    },
  },
  {
    songId: "l8e1Byk1Dx0",
    title: "TRUE LOVER (ft. 행주)",
    artist: "이세계오빠들",
    remix: "",
    reaction: "",
    date: 220918,
    start: 0,
    end: 200,
    like: 0,
    hourly: {
      views: 9108423,
      increase: 773,
      last: 13,
    },
  },
  {
    songId: "DPEtmqvaKqY",
    title: "팬서비스",
    artist: "고세구",
    remix: "",
    reaction: "",
    date: 220111,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 9839785,
      increase: 770,
      last: 20,
    },
  },
  {
    songId: "7XFJ4s0j9z0",
    title: "고속도로 로망스",
    artist: "주르르, 숲튽훈",
    remix: "",
    reaction: "",
    date: 230719,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 546066,
      increase: 761,
      last: 11,
    },
  },
  {
    songId: "eP-y5aHlqYo",
    title: "Hyperstar (ft. 프리터)",
    artist: "독고혜지",
    remix: "",
    reaction: "",
    date: 230729,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 210601,
      increase: 757,
      last: 19,
    },
  },
  {
    songId: "gEKKOrvh92Y",
    title: "아이돌 #Shorts",
    artist: "징버거",
    remix: "",
    reaction: "",
    date: 230612,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 3179578,
      increase: 713,
      last: 5,
    },
  },
  {
    songId: "qunpFTI90sU",
    title: "강풍 올백머리",
    artist: "징버거",
    remix: "",
    reaction: "JOWZiZWNjHg",
    date: 230426,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 2658540,
      increase: 693,
      last: 14,
    },
  },
  {
    songId: "6hEvgKL0ClA",
    title: "Promise",
    artist: "릴파",
    remix: "",
    reaction: "",
    date: 211229,
    start: 0,
    end: 243,
    like: 0,
    hourly: {
      views: 7310387,
      increase: 600,
      last: 16,
    },
  },
  {
    songId: "iLXmqg_HHRA",
    title: "스물셋",
    artist: "비챤",
    remix: "",
    reaction: "5pIR8SGmgkg",
    date: 230617,
    start: 0,
    end: 194,
    like: 0,
    hourly: {
      views: 1307204,
      increase: 573,
      last: 15,
    },
  },
  {
    songId: "K8WC6uWyC9I",
    title: "그냥 살아! (ft. 비챤)",
    artist: "김피탕앤짬뽕",
    remix: "",
    reaction: "",
    date: 220918,
    start: 16,
    end: 0,
    like: 0,
    hourly: {
      views: 8179572,
      increase: 560,
      last: 21,
    },
  },
  {
    songId: "--Go33WYnqw",
    title: "DAYBREAK FRONTLINE",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 200314,
    start: 0,
    end: 213,
    like: 0,
    hourly: {
      views: 4778473,
      increase: 531,
      last: 24,
    },
  },
  {
    songId: "YmELthNomns",
    title: "맘가는대로 (ft. 고세구)",
    artist: "세새한 캘리퍼스",
    remix: "",
    reaction: "",
    date: 220918,
    start: 0,
    end: 222,
    like: 0,
    hourly: {
      views: 5306715,
      increase: 523,
      last: 39,
    },
  },
  {
    songId: "suAKxhbbtVs",
    title: "약속해요",
    artist: "고세구",
    remix: "",
    reaction: "",
    date: 230728,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 126268,
      increase: 516,
      last: 17,
    },
  },
  {
    songId: "aK76gQHIm04",
    title: "징버거 궁시렁 (Remix by 레이지스피크)",
    artist: "징버거",
    remix: "",
    reaction: "zxVzfCawDyE",
    date: 221220,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 3400738,
      increase: 506,
      last: 18,
    },
  },
  {
    songId: "lLIpFxWtqCQ",
    title:
      "사랑하긴 했었나요 스쳐가는 인연이었나요 짧지않은 우리 함께했던 시간들이 자꾸 내 마음을 가둬두네 (Baby I need you)",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 221216,
    start: 0,
    end: 204,
    like: 0,
    hourly: {
      views: 3523410,
      increase: 499,
      last: 32,
    },
  },
  {
    songId: "JY-gJkMuJ94",
    title: "겨울봄",
    artist: "이세계아이돌",
    remix: "",
    reaction: "",
    date: 220311,
    start: 0,
    end: 238,
    like: 0,
    hourly: {
      views: 6408237,
      increase: 497,
      last: 23,
    },
  },
  {
    songId: "_lwD3ILdKi0",
    title: "무희",
    artist: "뢴트게늄",
    remix: "",
    reaction: "",
    date: 230225,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 3250296,
      increase: 486,
      last: 25,
    },
  },
  {
    songId: "lI1hkRxcUK8",
    title: "NIGHT DANCER (BIG Naughty Remix)",
    artist: "짬통스",
    remix: "",
    reaction: "",
    date: 230801,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 55074,
      increase: 473,
      last: 33,
    },
  },
  {
    songId: "Empfi8q0aas",
    title: "이세돌 사이퍼",
    artist: "이세계아이돌, 뢴트게늄",
    remix: "",
    reaction: "VVITtwPKW-E",
    date: 220423,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 6052449,
      increase: 461,
      last: 50,
    },
  },
  {
    songId: "qZi1Xh0_8q4",
    title: "긍지높은 아이돌",
    artist: "고세구",
    remix: "",
    reaction: "",
    date: 221203,
    start: 0,
    end: 253,
    like: 0,
    hourly: {
      views: 3227086,
      increase: 460,
      last: 35,
    },
  },
  {
    songId: "YZ0xA3LUzNQ",
    title: "ShowDown (ft. 아이네)",
    artist: "밴틀니",
    remix: "",
    reaction: "",
    date: 220918,
    start: 0,
    end: 251,
    like: 0,
    hourly: {
      views: 4570571,
      increase: 454,
      last: 34,
    },
  },
  {
    songId: "KjySNSxgg3U",
    title: "저곳으로",
    artist: "징버거",
    remix: "",
    reaction: "GZDoPjRpAoQ",
    date: 230531,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 1881744,
      increase: 451,
      last: 28,
    },
  },
  {
    songId: "eWaBljLkd08",
    title: "Ballin'",
    artist: "징버거",
    remix: "",
    reaction: "",
    date: 230525,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 753079,
      increase: 434,
      last: 57,
    },
  },
  {
    songId: "uG91iq0AzKM",
    title: "홍련화",
    artist: "고세구",
    remix: "",
    reaction: "",
    date: 230222,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 2644935,
      increase: 431,
      last: 41,
    },
  },
  {
    songId: "4rye8BP7GwY",
    title: "OVERDOSE",
    artist: "아이네",
    remix: "",
    reaction: "",
    date: 230306,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 542028,
      increase: 428,
      last: 44,
    },
  },
  {
    songId: "H02v7OU9Rtg",
    title: "타상연화",
    artist: "릴파, 릭파",
    remix: "",
    reaction: "",
    date: 230401,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 1493042,
      increase: 413,
      last: 26,
    },
  },
  {
    songId: "-in8F0zmLcM",
    title: "God Knows…",
    artist: "아이네",
    remix: "",
    reaction: "",
    date: 211125,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 3926873,
      increase: 411,
      last: 38,
    },
  },
  {
    songId: "K-5WdjbCYnk",
    title: "마지막 재회",
    artist: "릴파, 뢴트게늄",
    remix: "",
    reaction: "",
    date: 220605,
    start: 0,
    end: 254,
    like: 0,
    hourly: {
      views: 6469671,
      increase: 410,
      last: 29,
    },
  },
  {
    songId: "pl38om066m0",
    title: "전하지 못한 진심",
    artist: "해루석, 아이네, 릴파, 비챤",
    remix: "",
    reaction: "HiLXC6TWE2k",
    date: 220702,
    start: 5,
    end: 246,
    like: 0,
    hourly: {
      views: 4205531,
      increase: 404,
      last: 36,
    },
  },
  {
    songId: "1UbyyaDc8x0",
    title: "세계는 사랑에 빠져있어",
    artist: "릴파",
    remix: "",
    reaction: "",
    date: 220214,
    start: 19,
    end: 0,
    like: 0,
    hourly: {
      views: 4992798,
      increase: 396,
      last: 31,
    },
  },
  {
    songId: "JwEEIHzZNuQ",
    title: "Always with you",
    artist: "릴파",
    remix: "",
    reaction: "",
    date: 221209,
    start: 0,
    end: 228,
    like: 0,
    hourly: {
      views: 2480489,
      increase: 384,
      last: 22,
    },
  },
  {
    songId: "tT-kuonVzfY",
    title: "STAY",
    artist: "징버거",
    remix: "",
    reaction: "",
    date: 230120,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 2854401,
      increase: 384,
      last: 30,
    },
  },
  {
    songId: "08meo6qrhFc",
    title: "왁맥송 #Shorts",
    artist: "우왁굳",
    remix: "",
    reaction: "lzLZIcoYhPQ",
    date: 200922,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 5324726,
      increase: 382,
      last: 86,
    },
  },
  {
    songId: "p9TFQ9ySJLs",
    title: "봄도둑",
    artist: "징버거",
    remix: "",
    reaction: "",
    date: 230430,
    start: 0,
    end: 288,
    like: 0,
    hourly: {
      views: 1302318,
      increase: 377,
      last: 73,
    },
  },
  {
    songId: "z6RSOiYOVuQ",
    title: "아이돌 (ft. 비챤)",
    artist: "주르르",
    remix: "",
    reaction: "",
    date: 230517,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 1549996,
      increase: 374,
      last: 43,
    },
  },
  {
    songId: "owlLg3R9u6c",
    title: "How To Love (ft. 징버거)",
    artist: "OYT",
    remix: "",
    reaction: "",
    date: 220918,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 4172545,
      increase: 373,
      last: 55,
    },
  },
  {
    songId: "IK-z7xhiKB0",
    title: "PINK VENOM",
    artist: "저세계아이돌",
    remix: "",
    reaction: "Omf5lBoqBXU",
    date: 230702,
    start: 0,
    end: 186,
    like: 0,
    hourly: {
      views: 665180,
      increase: 356,
      last: 49,
    },
  },
  {
    songId: "dZc2K3lLcz4",
    title: "U R Man (암욜맨)",
    artist: "아닌말곰",
    remix: "",
    reaction: "dgqT4ORWMEo",
    date: 230612,
    start: 0,
    end: 201,
    like: 0,
    hourly: {
      views: 1102766,
      increase: 354,
      last: 42,
    },
  },
  {
    songId: "YZoeO3T7hsc",
    title: "부엉이",
    artist: "아이네",
    remix: "",
    reaction: "",
    date: 220223,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 3457772,
      increase: 345,
      last: 48,
    },
  },
  {
    songId: "EA_gei4Fcxk",
    title: "Hot Summer",
    artist: "러브 미쓰 피쓰",
    remix: "",
    reaction: "",
    date: 230612,
    start: 0,
    end: 229,
    like: 0,
    hourly: {
      views: 1525101,
      increase: 331,
      last: 37,
    },
  },
  {
    songId: "ME0m9X7q2UU",
    title: "Every Summertime",
    artist: "비밀소녀",
    remix: "",
    reaction: "",
    date: 230719,
    start: 13,
    end: 0,
    like: 0,
    hourly: {
      views: 121329,
      increase: 327,
      last: 58,
    },
  },
  {
    songId: "-ZFDUHgF48U",
    title: "SUMMER TIME",
    artist: "하쿠, 왁컬로이두",
    remix: "백수맛팬치",
    reaction: "J4MM1pRikBg",
    date: 220531,
    start: 11,
    end: 256,
    like: 0,
    hourly: {
      views: 3718253,
      increase: 323,
      last: 52,
    },
  },
  {
    songId: "Brf3LWwNVTk",
    title: "LOVE DIVE",
    artist: "이세계아이돌",
    remix: "",
    reaction: "",
    date: 220904,
    start: 0,
    end: 174,
    like: 0,
    hourly: {
      views: 4110144,
      increase: 320,
      last: 104,
    },
  },
  {
    songId: "7IcafhbXprU",
    title: "신호등",
    artist: "아이네",
    remix: "",
    reaction: "",
    date: 220419,
    start: 0,
    end: 229,
    like: 0,
    hourly: {
      views: 3358996,
      increase: 317,
      last: 66,
    },
  },
  {
    songId: "tc92ES3R6os",
    title: "봄 사랑 벚꽃 말고",
    artist: "주르르, 주폭소년단",
    remix: "",
    reaction: "",
    date: 230601,
    start: 14,
    end: 210,
    like: 0,
    hourly: {
      views: 581570,
      increase: 317,
      last: 54,
    },
  },
  {
    songId: "VcvMQ9MZhF8",
    title: "But You Want More",
    artist: "이세계아이돌",
    remix: "",
    reaction: "5ezxTdrpksk",
    date: 220215,
    start: 0,
    end: 197,
    like: 0,
    hourly: {
      views: 3472504,
      increase: 312,
      last: 77,
    },
  },
  {
    songId: "rFxJjpSeXHI",
    title: "SCIENTIST (ft. 아이네)",
    artist: "주르르",
    remix: "",
    reaction: "",
    date: 220314,
    start: 0,
    end: 197,
    like: 0,
    hourly: {
      views: 5409089,
      increase: 309,
      last: 67,
    },
  },
  {
    songId: "79rDMDll-IY",
    title: "Ballin'",
    artist: "두세븐 일레븐 FC",
    remix: "",
    reaction: "",
    date: 230313,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 1388674,
      increase: 308,
      last: 64,
    },
  },
  {
    songId: "LrVYuOXt0qs",
    title: "RE:WIND (Orchestra ver.)",
    artist: "영바이브",
    remix: "",
    reaction: "",
    date: 230726,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 146003,
      increase: 305,
      last: 62,
    },
  },
  {
    songId: "OTkFJyn4mvc",
    title: "투니버스 메들리",
    artist: "이세계아이돌",
    remix: "",
    reaction: "",
    date: 211205,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 4763288,
      increase: 305,
      last: 40,
    },
  },
  {
    songId: "RfMQaLikvX8",
    title: "3년째의 바람",
    artist: "아마타인",
    remix: "",
    reaction: "",
    date: 230707,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 409891,
      increase: 303,
      last: 70,
    },
  },
  {
    songId: "sP0E6y0gWxA",
    title: "Tot Musica",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 230423,
    start: 0,
    end: 193,
    like: 0,
    hourly: {
      views: 1044399,
      increase: 301,
      last: 78,
    },
  },
  {
    songId: "1ePxevNqM2s",
    title: "융터르 (Full Ver.)",
    artist: "왁컬로이두",
    remix: "CLTH",
    reaction: "rmRPfxDlphg",
    date: 230310,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 2052599,
      increase: 298,
      last: 46,
    },
  },
  {
    songId: "X7cO4xQ5Gqs",
    title: "M@STERPIECE",
    artist: "주르르",
    remix: "",
    reaction: "",
    date: 220507,
    start: 0,
    end: 340,
    like: 0,
    hourly: {
      views: 2521197,
      increase: 298,
      last: 123,
    },
  },
  {
    songId: "3XoZ8MsphNw",
    title: "미리 메리 크리스마스 (ft. 천양)",
    artist: "징버거, 주르르, 비챤",
    remix: "",
    reaction: "",
    date: 221225,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 960968,
      increase: 291,
      last: 1452,
    },
  },
  {
    songId: "mqcGI5QGmzk",
    title: "계절범죄",
    artist: "이노리(지하돌), 흰젓가락(주폭), 우앵두(지하돌)",
    remix: "",
    reaction: "CN8cZabPVgM",
    date: 230630,
    start: 0,
    end: 229,
    like: 0,
    hourly: {
      views: 285795,
      increase: 289,
      last: 101,
    },
  },
  {
    songId: "ZLQc1yuUOAM",
    title: "참새",
    artist: "고세구",
    remix: "",
    reaction: "",
    date: 230329,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 1710211,
      increase: 288,
      last: 51,
    },
  },
  {
    songId: "TVl0QFpGE-E",
    title: "우왁'굿' (삶이 안 풀릴 땐 우왁굿을 하자)",
    artist: "팬치",
    remix: "",
    reaction: "5hy6eOUG9m4",
    date: 221227,
    start: 0,
    end: 238,
    like: 0,
    hourly: {
      views: 701029,
      increase: 287,
      last: 71,
    },
  },
  {
    songId: "pDzR-0_zwXk",
    title: "잠깐나올래",
    artist: "해루석",
    remix: "",
    reaction: "",
    date: 230327,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 1737428,
      increase: 274,
      last: 45,
    },
  },
  {
    songId: "G0g3d6b5CZM",
    title: "Choose me",
    artist: "주르르, 뢴트게늄, 징버거",
    remix: "",
    reaction: "",
    date: 220128,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 3263013,
      increase: 273,
      last: 91,
    },
  },
  {
    songId: "S2I6tRQtR58",
    title: "Grrr",
    artist: "왁컬로이두",
    remix: "큐컴버",
    reaction: "beBJf_eifnY",
    date: 230702,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 319283,
      increase: 272,
      last: 75,
    },
  },
  {
    songId: "Ozpfl_7_nwc",
    title: "추격자 (The Chaser)",
    artist: "GTS",
    remix: "",
    reaction: "",
    date: 230612,
    start: 5,
    end: 0,
    like: 0,
    hourly: {
      views: 806237,
      increase: 268,
      last: 72,
    },
  },
  {
    songId: "NVns4yRoTlU",
    title: "취기를 빌려",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 220309,
    start: 0,
    end: 0,
    like: 1,
    hourly: {
      views: 3927854,
      increase: 268,
      last: 56,
    },
  },
  {
    songId: "C6ROi2MySL8",
    title: "HEADLINE (헤드라인)",
    artist: "해루석, 곽춘식, 히키킹",
    remix: "",
    reaction: "JepqpVkDhEY",
    date: 221102,
    start: 0,
    end: 158,
    like: 0,
    hourly: {
      views: 2273747,
      increase: 265,
      last: 63,
    },
  },
  {
    songId: "_OsnBqrh6yg",
    title: "어푸",
    artist: "주르르",
    remix: "",
    reaction: "",
    date: 221023,
    start: 0,
    end: 199,
    like: 0,
    hourly: {
      views: 2427707,
      increase: 264,
      last: 84,
    },
  },
  {
    songId: "9soAWkBqXyw",
    title: "BOY",
    artist: "짬통스",
    remix: "",
    reaction: "LnGSrNKCPmM",
    date: 230405,
    start: 6,
    end: 237,
    like: 0,
    hourly: {
      views: 1100727,
      increase: 262,
      last: 61,
    },
  },
  {
    songId: "w1kTv8iUx9w",
    title: "사랑을 전하고 싶다던가",
    artist: "비챤",
    remix: "",
    reaction: "jW03jp-YWwc",
    date: 200413,
    start: 0,
    end: 231,
    like: 0,
    hourly: {
      views: 1466367,
      increase: 254,
      last: 79,
    },
  },
  {
    songId: "IzrIYIqlBnA",
    title: "피날레 (ft. 릴파)",
    artist: "레이디버그",
    remix: "",
    reaction: "",
    date: 220918,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 3061537,
      increase: 251,
      last: 92,
    },
  },
  {
    songId: "8tJb1YlMHfA",
    title: "너로피어오라 (Flowering)",
    artist: "릴파",
    remix: "",
    reaction: "",
    date: 220331,
    start: 0,
    end: 224,
    like: 0,
    hourly: {
      views: 2619004,
      increase: 249,
      last: 90,
    },
  },
  {
    songId: "bwgR3hAR7nQ",
    title: "Popular",
    artist: "아이네",
    remix: "",
    reaction: "",
    date: 230215,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 806613,
      increase: 248,
      last: 65,
    },
  },
  {
    songId: "63zca7DAoFA",
    title: "이쪼기야 도와줘 #Shorts",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 230701,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 323289,
      increase: 244,
      last: 69,
    },
  },
  {
    songId: "fzHJxq37cqI",
    title: "사랑은 은하수 다방에서 (Love in the Milky Way Cafe)",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 220430,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 2789880,
      increase: 237,
      last: 140,
    },
  },
  {
    songId: "TYB9ScXvq34",
    title: "우마뾰이 전설",
    artist: "이세계아이돌",
    remix: "",
    reaction: "",
    date: 220823,
    start: 0,
    end: 135,
    like: 0,
    hourly: {
      views: 2967194,
      increase: 236,
      last: 106,
    },
  },
  {
    songId: "5tGwnxu8NIw",
    title: "Gaea.Zero",
    artist: "릴파",
    remix: "",
    reaction: "",
    date: 230615,
    start: 0,
    end: 206,
    like: 0,
    hourly: {
      views: 392131,
      increase: 228,
      last: 114,
    },
  },
  {
    songId: "kra0f71EIgc",
    title: "TOMBOY (ft. 고세구)",
    artist: "징버거",
    remix: "",
    reaction: "",
    date: 220530,
    start: 6,
    end: 180,
    like: 0,
    hourly: {
      views: 4093071,
      increase: 219,
      last: 102,
    },
  },
  {
    songId: "BMywKiOgT90",
    title: "꽃에 망령",
    artist: "고세구",
    remix: "",
    reaction: "",
    date: 230730,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 28543,
      increase: 217,
      last: 85,
    },
  },
  {
    songId: "xAr7ADitQU0",
    title: "강풍 올백머리",
    artist: "하쿠",
    remix: "",
    reaction: "",
    date: 230420,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 1203394,
      increase: 213,
      last: 99,
    },
  },
  {
    songId: "4ZjDoG0bc5Q",
    title: "SATELLITES",
    artist: "릴파",
    remix: "",
    reaction: "",
    date: 230504,
    start: 0,
    end: 230,
    like: 0,
    hourly: {
      views: 571059,
      increase: 212,
      last: 108,
    },
  },
  {
    songId: "27X16XuxSq0",
    title: "망령혼합대무도회",
    artist: "짬통스",
    remix: "",
    reaction: "CUoPA8oZijw",
    date: 220925,
    start: 8,
    end: 232,
    like: 0,
    hourly: {
      views: 2210002,
      increase: 208,
      last: 89,
    },
  },
  {
    songId: "kHpvUymXXEg",
    title: "KICK BACK #Shorts",
    artist: "왁네즈 켄시",
    remix: "왁톡",
    reaction: "WsO3ikDyk8A",
    date: 230216,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 4338666,
      increase: 207,
      last: 68,
    },
  },
  {
    songId: "tZtskWzmpXs",
    title: "드리밍 츄츄",
    artist: "하쿠, 왁컬로이두",
    remix: "추르르",
    reaction: "fqtMSSf31P0",
    date: 220211,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 3601092,
      increase: 205,
      last: 144,
    },
  },
  {
    songId: "tGMDqdUOeD8",
    title: "M자 탈모 (ft. 프리터)",
    artist: "소피아, 도파민박사",
    remix: "",
    reaction: "VcyCdwOCwTw",
    date: 230610,
    start: 8,
    end: 190,
    like: 0,
    hourly: {
      views: 487205,
      increase: 203,
      last: 60,
    },
  },
  {
    songId: "EUVVDRbg_p4",
    title: "Sis puella magica!",
    artist: "아이네",
    remix: "",
    reaction: "",
    date: 230602,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 272796,
      increase: 195,
      last: 135,
    },
  },
  {
    songId: "xBiOm4-fkU4",
    title: "Henceforth",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 200703,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 1940921,
      increase: 189,
      last: 27,
    },
  },
  {
    songId: "nvBG4zYkJ-c",
    title: "Happy Together",
    artist: "해루석, 비밀소녀",
    remix: "",
    reaction: "",
    date: 221223,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 1449891,
      increase: 188,
      last: 76,
    },
  },
  {
    songId: "-pczFfMtWrc",
    title: "귀여워서 미안해",
    artist: "주르르",
    remix: "",
    reaction: "",
    date: 230115,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 1562540,
      increase: 186,
      last: 95,
    },
  },
  {
    songId: "yYHKUyPrc24",
    title: "하쿠 (HAKU)",
    artist: "새우튀김, 하쿠",
    remix: "",
    reaction: "BsN3_x8_Q9s",
    date: 220405,
    start: 0,
    end: 244,
    like: 0,
    hourly: {
      views: 2269355,
      increase: 186,
      last: 81,
    },
  },
  {
    songId: "8QRrNxCfXh8",
    title: "나의 청춘들에게 (ft. 곽춘식)",
    artist: "도파민박사",
    remix: "",
    reaction: "vGW0UcOKCVQ",
    date: 230423,
    start: 7,
    end: 251,
    like: 0,
    hourly: {
      views: 821654,
      increase: 182,
      last: 94,
    },
  },
  {
    songId: "wSG93VZoMFg",
    title: "In Romantic",
    artist: "해루석",
    remix: "",
    reaction: "",
    date: 221225,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 601139,
      increase: 177,
      last: 1224,
    },
  },
  {
    songId: "7D8wnXs4zSU",
    title: "Fire Again",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 220902,
    start: 0,
    end: 0,
    like: 0,
    hourly: {
      views: 1446109,
      increase: 177,
      last: 120,
    },
  },
  {
    songId: "P-wOE92vfyk",
    title: "유령도쿄",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 210116,
    start: 0,
    end: 201,
    like: 0,
    hourly: {
      views: 2408195,
      increase: 177,
      last: 53,
    },
  },
];

export const recommended = [
  {
    key: "best",
    title: "역대 왁뮤 1위",
    public: true,
    createAt: 1686382026000,
    image: {
      round: 1,
      square: 1,
    },
    songs: [],
  },
  {
    key: "official",
    title: "ALL : MUSIC",
    public: true,
    createAt: 1686382026000,
    image: {
      round: 1,
      square: 1,
    },
    songs: [],
  },
  {
    key: "gomemsong",
    title: "가요제&학예회",
    public: true,
    createAt: 1675316173132,
    image: {
      round: 2,
      square: 2,
    },
    songs: [],
  },
  {
    key: "competition",
    title: "연말공모전",
    public: true,
    createAt: 1675316173132,
    image: {
      round: 2,
      square: 2,
    },
    songs: [],
  },
  {
    key: "carol",
    title: "캐롤",
    public: true,
    createAt: 1675316173132,
    image: {
      round: 2,
      square: 2,
    },
    songs: [],
  },
  {
    key: "hiphop",
    title: "힙합 SWAG",
    public: true,
    createAt: 1675316173132,
    image: {
      round: 2,
      square: 2,
    },
    songs: [],
  },
  {
    key: "worksong",
    title: "노동요",
    public: true,
    createAt: 1675316173132,
    image: {
      round: 2,
      square: 2,
    },
    songs: [],
  },
  {
    key: "confidence",
    title: "자신감 충전",
    public: true,
    createAt: 1686382026000,
    image: {
      round: 1,
      square: 1,
    },
    songs: [],
  },
];

export const songList: SongsSearchResponse = {
  song: [
    {
      songId: "K8WC6uWyC9I",
      title: "그냥 살아! (ft. 비챤)",
      artist: "김피탕앤짬뽕",
      remix: "",
      reaction: "",
      date: 220918,
      start: 16,
      end: 0,
      like: 0,
      total: { views: 7952476, increase: 319, last: 4 },
    },
    {
      songId: "TriBGtGgnuI",
      title: "기어와라 망냥냥양",
      artist: "비챤",
      remix: "큐컴버",
      reaction: "SlFfF_jdjUY",
      date: 220606,
      start: 0,
      end: 78,
      like: 0,
      total: { views: 634003, increase: 2, last: 228 },
    },
    {
      songId: "2kYrlukIXm4",
      title: "망냥냥캣 #Shorts",
      artist: "비챤",
      remix: "위윌왁휴",
      reaction: "",
      date: 220806,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 237721, increase: 0, last: 465 },
    },
    {
      songId: "Vt0lSTxSjaw",
      title:
        "Whatever (ft. 율음, 키드밀리, 그냥노창, The Quiett, Raf Sandou) (doubling. 히키킹)",
      artist: "sAewoo",
      remix: "",
      reaction: "",
      date: 220418,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 146842, increase: 0, last: 598 },
    },
    {
      songId: "WQApknUVDDg",
      title: "그냥 살아! (ft. 왁컬로이두)",
      artist: "비챤, 아컬로이드, 고컬로이드",
      remix: "꽃세계",
      reaction: "V92zyZobGLY",
      date: 221005,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 103967, increase: 0, last: 710 },
    },
    {
      songId: "oz5AoL3ovfA",
      title: "그냥 살아!&맘가는대로 (Live Ver.)",
      artist: "주르르",
      remix: "",
      reaction: "",
      date: 221218,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 63102, increase: 0, last: 851 },
    },
    {
      songId: "P8o69SEkBv4",
      title: "그냥 살아! (8bit Remix)",
      artist: "김피탕앤짬뽕",
      remix: "OVERSANS",
      reaction: "",
      date: 221014,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 10217, increase: 0, last: 1392 },
    },
    {
      songId: "SVbkvrB6Kvo",
      title: "비챤이 우와하고 망냥냥이 모찌모찌",
      artist: "비챤",
      remix: "Recci",
      reaction: "",
      date: 230219,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 7272, increase: 0, last: 1519 },
    },
    {
      songId: "P38Fs8bPPK8",
      title: "냥뇽갈비 #Shorts",
      artist: "징버거",
      remix: "kingbadnae",
      reaction: "",
      date: 230317,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 4698, increase: 0, last: 1635 },
    },
    {
      songId: "_Ulq7vQePSU",
      title: "그냥 살아",
      artist: "클리보",
      remix: "",
      reaction: "",
      date: 221222,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 4658, increase: 0, last: 1640 },
    },
    {
      songId: "kxufR-QnvkI",
      title: "너는 그냥 가만히 있으면 돼",
      artist: "왁컬로이두",
      remix: "해원이",
      reaction: "",
      date: 230129,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 1369, increase: 0, last: 1875 },
    },
  ],
  artist: [
    {
      songId: "NVm8Uzai9HY",
      title: "없는계절 (ft. 아이네, 씨잼, 윤훼이)",
      artist: "그냥노창",
      remix: "",
      reaction: "",
      date: 220402,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 343114, increase: 2, last: 357 },
    },
    {
      songId: "I92GTsOVG7E",
      title: "Whatever 가녹음 실패작 (doubling. 히키킹)",
      artist: "그냥노창",
      remix: "",
      reaction: "",
      date: 220418,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 321462, increase: 6, last: 378 },
    },
    {
      songId: "XFh92D_F03w",
      title: "Oh wow!",
      artist: "챤컬로이드, 망냥냥",
      remix: "큐컴버",
      reaction: "",
      date: 230622,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 33193, increase: 27, last: 1033 },
    },
  ],
  remix: [
    {
      songId: "9JzFQ_nJElk",
      title: "되감난 고장기버튼 (ft. 우왁굳)",
      artist: "이세계아이돌, 히키킹",
      remix: "그냥노창",
      reaction: "",
      date: 211229,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 98753, increase: 1, last: 723 },
    },
    {
      songId: "BxJFFFEQC48",
      title: "TRUE LOVER Remix",
      artist: "이세계오빠들",
      remix: "그냥노창",
      reaction: "",
      date: 221014,
      start: 0,
      end: 0,
      like: 0,
      total: { views: 33394, increase: 0, last: 1032 },
    },
    {
      songId: "OCimjWl9d8I",
      title: "겨울봄 Remix",
      artist: "이세계아이돌",
      remix: "그냥노창",
      reaction: "",
      date: 220813,
      start: 0,
      end: 108,
      like: 0,
      total: { views: 26135, increase: 1, last: 1090 },
    },
  ],
};

export const profileList = [
  {
    type: "panchi",
    version: 2,
  },
  {
    type: "ifari",
    version: 2,
  },
  {
    type: "dulgi",
    version: 2,
  },
  {
    type: "bat",
    version: 2,
  },
  {
    type: "segyun",
    version: 2,
  },
  {
    type: "gorani",
    version: 2,
  },
  {
    type: "jupock",
    version: 2,
  },
  {
    type: "ddong",
    version: 2,
  },
];

export const myListSongs = [
  {
    songId: "QgMFpuos4Rg",
    title: "LOCKDOWN",
    artist: "이세계아이돌",
    remix: "",
    reaction: "",
    date: 230622,
    start: 0,
    end: 0,
    like: 1,
    total: { views: 3004739, increase: 2894, last: 1 },
  },
  {
    songId: "SXE-gIU3yJs",
    title: "고멤가요제 MASHUP",
    artist: "아이네",
    remix: "",
    reaction: "",
    date: 221201,
    start: 0,
    end: 0,
    like: 0,
    total: { views: 5105546, increase: 740, last: 3 },
  },
  {
    songId: "iLXmqg_HHRA",
    title: "스물셋",
    artist: "비챤",
    remix: "",
    reaction: "5pIR8SGmgkg",
    date: 230617,
    start: 0,
    end: 192,
    like: 0,
    total: { views: 883975, increase: 710, last: 2 },
  },
  {
    songId: "fgSXAKsq-Vo",
    title: "리와인드 (RE:WIND)",
    artist: "이세계아이돌",
    remix: "",
    reaction: "",
    date: 211222,
    start: 0,
    end: 270,
    like: 0,
    total: { views: 15676550, increase: 654, last: 4 },
  },
  {
    songId: "aK76gQHIm04",
    title: "징버거 궁시렁 Remix",
    artist: "징버거",
    remix: "레이지스피크",
    reaction: "zxVzfCawDyE",
    date: 221220,
    start: 0,
    end: 0,
    like: 0,
    total: { views: 3028840, increase: 578, last: 5 },
  },
  {
    songId: "IK-z7xhiKB0",
    title: "PINK VENOM",
    artist: "저세계아이돌",
    remix: "",
    reaction: "",
    date: 230702,
    start: 0,
    end: 186,
    like: 0,
    total: { views: 283411, increase: 558, last: 6 },
  },
  {
    songId: "EA_gei4Fcxk",
    title: "Hot Summer",
    artist: "러브 미쓰 피쓰",
    remix: "",
    reaction: "",
    date: 230612,
    start: 0,
    end: 229,
    like: 0,
    total: { views: 1300552, increase: 479, last: 14 },
  },
  {
    songId: "DPEtmqvaKqY",
    title: "팬서비스",
    artist: "고세구",
    remix: "",
    reaction: "",
    date: 220111,
    start: 0,
    end: 0,
    like: 0,
    total: { views: 9540461, increase: 462, last: 8 },
  },
  {
    songId: "qunpFTI90sU",
    title: "강풍 올백머리",
    artist: "징버거",
    remix: "",
    reaction: "JOWZiZWNjHg",
    date: 230426,
    start: 0,
    end: 0,
    like: 0,
    total: { views: 2321698, increase: 462, last: 16 },
  },
  {
    songId: "gEKKOrvh92Y",
    title: "아이돌 #Shorts",
    artist: "징버거",
    remix: "",
    reaction: "",
    date: 230612,
    start: 0,
    end: 0,
    like: 0,
    total: { views: 2545825, increase: 449, last: 13 },
  },
  {
    songId: "l8e1Byk1Dx0",
    title: "TRUE LOVER (ft. 행주)",
    artist: "이세계오빠들",
    remix: "",
    reaction: "",
    date: 220918,
    start: 0,
    end: 200,
    like: 0,
    total: { views: 8805280, increase: 446, last: 7 },
  },
  {
    songId: "_lwD3ILdKi0",
    title: "무희",
    artist: "뢴트게늄",
    remix: "",
    reaction: "",
    date: 230225,
    start: 0,
    end: 0,
    like: 0,
    total: { views: 2979593, increase: 444, last: 9 },
  },
  {
    songId: "6hEvgKL0ClA",
    title: "Promise",
    artist: "릴파",
    remix: "",
    reaction: "",
    date: 211229,
    start: 0,
    end: 243,
    like: 0,
    total: { views: 7047127, increase: 440, last: 10 },
  },
  {
    songId: "mqcGI5QGmzk",
    title: "계절범죄",
    artist: "이노리(지하돌), 흰젓가락(주폭), 우앵두(지하돌)",
    remix: "",
    reaction: "CN8cZabPVgM",
    date: 230630,
    start: 0,
    end: 229,
    like: 0,
    total: { views: 118503, increase: 430, last: 15 },
  },
  {
    songId: "S2I6tRQtR58",
    title: "Grrr",
    artist: "왁컬로이두",
    remix: "큐컴버",
    reaction: "beBJf_eifnY",
    date: 230702,
    start: 0,
    end: 0,
    like: 0,
    total: { views: 132930, increase: 422, last: 27 },
  },
  {
    songId: "p9TFQ9ySJLs",
    title: "봄도둑",
    artist: "징버거",
    remix: "",
    reaction: "",
    date: 230430,
    start: 0,
    end: 288,
    like: 0,
    total: { views: 1084810, increase: 402, last: 18 },
  },
  {
    songId: "lLIpFxWtqCQ",
    title:
      "사랑하긴 했었나요 스쳐가는 인연이었나요 짧지않은 우리 함께했던 시간들이 자꾸 내 마음을 가둬두네 (Baby I need you)",
    artist: "비챤",
    remix: "",
    reaction: "",
    date: 221216,
    start: 0,
    end: 0,
    like: 0,
    total: { views: 3307240, increase: 371, last: 12 },
  },
  {
    songId: "KjySNSxgg3U",
    title: "저곳으로",
    artist: "징버거",
    remix: "",
    reaction: "GZDoPjRpAoQ",
    date: 230531,
    start: 0,
    end: 0,
    like: 0,
    total: { views: 1632994, increase: 335, last: 11 },
  },
  {
    songId: "eWaBljLkd08",
    title: "Ballin'",
    artist: "징버거",
    remix: "",
    reaction: "",
    date: 230525,
    start: 0,
    end: 0,
    like: 0,
    total: { views: 580998, increase: 333, last: 21 },
  },
  {
    songId: "K8WC6uWyC9I",
    title: "그냥 살아! (ft. 비챤)",
    artist: "김피탕앤짬뽕",
    remix: "",
    reaction: "",
    date: 220918,
    start: 16,
    end: 0,
    like: 0,
    total: { views: 7952476, increase: 319, last: 23 },
  },
];

export const dumyListItem = {
  key: "key1",
  index: -1,
  title: "리스트제목열두글자자자자",
  createAt: 1684622625731,
  user: {
    displayName: "이름",
    profile: {
      type: "gorani",
      version: 2,
    },
  },
  image: {
    name: "1",
    version: 11,
  },
  songs: myListSongs,
};

export const myList = [
  {
    key: "key1",
    title: "플레이리스트 1",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 1,
    },
    songs: myListSongs,
  },
  {
    key: "key2",
    title: "플레이리스트 2",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 7,
    },
    songs: myListSongs,
  },
  {
    key: "key3",
    title: "플레이리스트 3",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 3,
    },
    songs: myListSongs,
  },
  {
    key: "key4",
    title: "플레이리스트 4",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 11,
    },
    songs: myListSongs,
  },
  {
    key: "key5",
    title: "플레이리스트 5",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 5,
    },
    songs: myListSongs,
  },
  {
    key: "key6",
    title: "플레이리스트 6",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 6,
    },
    songs: myListSongs,
  },
  {
    key: "key7",
    title: "플레이리스트 7",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 7,
    },
    songs: myListSongs,
  },
  {
    key: "key8",
    title: "플레이리스트 8",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 8,
    },
    songs: myListSongs,
  },
  {
    key: "key9",
    title: "플레이리스트 9",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 9,
    },
    songs: myListSongs,
  },
  {
    key: "key10",
    title: "플레이리스트 10",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 10,
    },
    songs: myListSongs,
  },
  {
    key: "key11",
    title: "플레이리스트 11",
    createAt: 1684622625731,
    user: {
      displayName: "이름",
      profile: {
        type: "gorani",
        version: 2,
      },
    },
    image: {
      name: "1",
      version: 11,
    },
    songs: myListSongs,
  },
];
