export const chartUpdated = "1688630567";

export const hourlyChart = [
  {
    songId: "Yn2rnQsv8bE",
    title: "울산왕감자 #Shorts",
    artist: "징버거",
    remix: "",
    reaction: "",
    date: 230706,
    start: 0,
    end: 0,
    hourly: {
      views: 18229,
      increase: 18229,
      last: 0,
    },
  },
  {
    songId: "QgMFpuos4Rg",
    title: "LOCKDOWN",
    artist: "이세계아이돌",
    remix: "",
    reaction: "",
    date: 230622,
    start: 0,
    end: 0,
    hourly: {
      views: 3025518,
      increase: 4135,
      last: 1,
    },
  },
  {
    songId: "iLXmqg_HHRA",
    title: "스물셋",
    artist: "비챤",
    remix: "",
    reaction: "5pIR8SGmgkg",
    date: 230617,
    start: 0,
    end: 192,
    hourly: {
      views: 889788,
      increase: 1176,
      last: 2,
    },
  },
  {
    songId: "gEKKOrvh92Y",
    title: "아이돌 #Shorts",
    artist: "징버거",
    remix: "",
    reaction: "",
    date: 230612,
    start: 0,
    end: 0,
    hourly: {
      views: 2550020,
      increase: 1107,
      last: 7,
    },
  },
  {
    songId: "fgSXAKsq-Vo",
    title: "리와인드 (RE:WIND)",
    artist: "이세계아이돌",
    remix: "",
    reaction: "",
    date: 211222,
    start: 0,
    end: 270,
    hourly: {
      views: 15681544,
      increase: 1082,
      last: 4,
    },
  },
  {
    songId: "SXE-gIU3yJs",
    title: "고멤가요제 MASHUP",
    artist: "아이네",
    remix: "",
    reaction: "",
    date: 221201,
    start: 0,
    end: 0,
    hourly: {
      views: 5110551,
      increase: 1037,
      last: 3,
    },
  },
  {
    songId: "aK76gQHIm04",
    title: "징버거 궁시렁 Remix",
    artist: "징버거",
    remix: "레이지스피크",
    reaction: "zxVzfCawDyE",
    date: 221220,
    start: 0,
    end: 0,
    hourly: {
      views: 3033481,
      increase: 985,
      last: 5,
    },
  },
  {
    songId: "IK-z7xhiKB0",
    title: "PINK VENOM",
    artist: "저세계아이돌",
    remix: "",
    reaction: "",
    date: 230702,
    start: 0,
    end: 186,
    hourly: {
      views: 287813,
      increase: 943,
      last: 6,
    },
  },
];

export const recommended = [
  {
    key: "best",
    title: "역대 왁뮤 1위",
    public: true,
    createAt: 1686382026000,
    image: {
      round: 1,
      square: 1,
    },
  },
  {
    key: "official",
    title: "ALL : MUSIC",
    public: true,
    createAt: 1686382026000,
    image: {
      round: 1,
      square: 1,
    },
  },
  {
    key: "gomemsong",
    title: "가요제&학예회",
    public: true,
    createAt: 1675316173132,
    image: {
      round: 2,
      square: 2,
    },
  },
  {
    key: "competition",
    title: "연말공모전",
    public: true,
    createAt: 1675316173132,
    image: {
      round: 2,
      square: 2,
    },
  },
  {
    key: "carol",
    title: "캐롤",
    public: true,
    createAt: 1675316173132,
    image: {
      round: 2,
      square: 2,
    },
  },
  {
    key: "hiphop",
    title: "힙합 SWAG",
    public: true,
    createAt: 1675316173132,
    image: {
      round: 2,
      square: 2,
    },
  },
  {
    key: "worksong",
    title: "노동요",
    public: true,
    createAt: 1675316173132,
    image: {
      round: 2,
      square: 2,
    },
  },
  {
    key: "confidence",
    title: "자신감 충전",
    public: true,
    createAt: 1686382026000,
    image: {
      round: 1,
      square: 1,
    },
  },
];
